### ISSUE TITLE
Don't forget expenditure data.

### ISSUE THREAD

**Issue by karichisholm** [18F/FEC#10]
There are quite a few websites that attempt to make FEC data more transparent and approachable.  But (almost?) all of them focus exclusively on the contribution side.  And while transparency about contributions is good, there are very strong reasons to make expenditures transparent as well.  Among those reasons:

* When funds are donated from one committee to another, there should always be a disclosed expenditure that matches a disclosed contribution. If that doesn't happen, something hinky is going on.  Even when fully disclosed, a pattern of rapid committee transfers can reveal the rough equivalent of political "money laundering" to hide the original source of funds.

* Historians, political scientists, and public interest researchers (and political opponents) will find expenditure patterns useful to understand how campaigns execute their chosen strategies.

* Studying expenditures can also lead to revelations of misconduct by campaigns, like candidates that use funds for personal expenses, inappropriate payoffs to political supporters, cronyism, etc.

**Comment by LindsayYoung** [comment]
There were a lot of thoughts here but, the main point, having expenditure data in the API and website is part of the beta https://beta.fec.gov/data/disbursements/

Feel free to open additional issues with other aspects of this data. 

As always, thanks for writing in!
