### ISSUE TITLE
The next general election for the presidency is not in 2018

### ISSUE THREAD

**Issue by jeremiak** [18F/FEC#1145]
From the beta.fec.gov homepage, I went to the "Citizen Information" section and entered my zip code. As a result, I saw the offices for my district in the upcoming election, but it also showed that the next general election for the US president is in November 2018, when in fact it is in 2020.

Screenshot:
<img width="551" alt="screen shot 2017-02-28 at 12 54 22 pm" src="https://cloud.githubusercontent.com/assets/780941/23446697/b141d16e-fe13-11e6-9659-cfdc13f247c0.png">

Source URL: https://beta.fec.gov/data/elections/?cycle=2018&state=NY&district=12

**Comment by jenniferthibault** [comment]
Hey Jeremia! Thanks for capturing this. We're tracking work against it this sprint in https://github.com/18F/openFEC-web-app/issues/1753 which will do a better job explaining the technical side of why this is happening (if you're curious) than I can!
