### ISSUE TITLE
Bug: Map overlapping with tabs

### ISSUE THREAD

**Issue by gemfarmer** [18F/FEC#1151]
The district map at [/data/elections/house/MN/05/2018/](https://beta.fec.gov/data/elections/house/MN/05/2018/) appears to be overlapping with the tabs to the left at certain screen widths. It appears to be doing it for other districts as well.

![screen shot 2017-03-02 at 3 55 18 pm](https://cloud.githubusercontent.com/assets/4803473/23528910/18727552-ff61-11e6-8b12-c9bf7b801e9b.png)

**Comment by noahmanger** [comment]
Thanks @gemfarmer !

**Comment by noahmanger** [comment]
Resolved!
