### ISSUE TITLE
Request: Add FEC report ID to /committee/{committee_id}/reports/

### ISSUE THREAD

**Issue by KatzIsPolitical** [18F/FEC#116]
The "FEC report ID" is required when committees are filing amendments to FEC reports. Currently, this is only available by going to the website and manually searching.  Including this report ID in the API will ease the process of filing amendments.

![capture](https://cloud.githubusercontent.com/assets/15451076/10851674/a5941ebc-7ee9-11e5-8fe1-28cee73aa787.PNG)

**Comment by LindsayYoung** [comment]
Moving conversation to 18F/openFEC#1355
