### ISSUE TITLE
Consult with non-profit watchdog organizations

### ISSUE THREAD

**Issue by DanielSchuman** [18F/FEC#12]
There are many non-profit organizations that regularly monitor the FEC's website but may not have seen your blogpost (or be sophisticated enough to use GitHub).

I suggest setting up meetings with :
* The Center for Responsive Politics (OpenSecrets)
* National Institute of Money in State Politics (NIMSBP)
* CREW (although I'm writing on our behalf)
* The Campaign Legal Center
* The Sunlight Foundation
* Democracy 21
* The Brennan Center
* Possibly the American Bar Association

There are also many legal practitioners who track this on a regular basis.

I would be happy to help set up some of these meetings.

**Comment by LindsayYoung** [comment]
Hey @DanielSchuman, 

We have been reaching out to civil society organizations, journalists, experts and concerned citizens.  Anyone who would like to participate in our user centered design process should sign up using the feedback tool on the website,GitHub or email.

Thanks for writing in!

**Comment by DanielSchuman** [comment]
If you have a brief intro of this new step, I'd be more than glad to send
it around using old-fashioned email. :)
