### ISSUE TITLE
Request: Data Download

### ISSUE THREAD

**Issue by onezerojeremy** [18F/FEC#130]
From email (from a usability tester): 

>Hi Jeremy,
 
>I rec’d an email saying fec.gov was in beta test and so I’m working in it. I realize it’s a work in progress, but is there a way yet to download candidate disbursement data?  I can bring up a candidate and I can bring up disbursements – but I can’t see how to export it to Excel. Does that function exist yet?

**Comment by leahbannon** [comment]
.csv downloads are available now for candidates and committees, and coming soon for other data.
