### ISSUE TITLE
Data issue: Independent expenditures missing on committee MARY GRAYDON - FONTANA

### ISSUE THREAD

**Issue by jenniferthibault** [18F/FEC#136]
As reported in https://github.com/18F/FEC/issues/134#issuecomment-154439113

@jwchumley pointed out: 
> the independent expenditures are in the source data. Are they not in the transferred data? There are 9 IEs all supporting Bernie Sanders.

URL: https://beta.fec.gov/data/committee/C90015579/?cycle=2016&amp;tab=summary

**Comment by jmcarp** [comment]
To clarify, is the issue that we aren't showing itemized IEs? The top-line expenditure and contribution numbers here seem to be correct (as compared to the DW and FECP tables, and the source filing).

**Comment by jwchumley** [comment]
Yes. The totals are there but the transactions aren't

**Comment by jmcarp** [comment]
Got it. We don't currently expose itemized individual expenditures, or custom aggregates thereof. I believe that's captured in our story map but not assigned to anybody. If this is a high priority, let's discuss further at sprint planning.

In the meantime, if the "Disbursements" column is always going to be empty for IE committees, we may want to hide it until we have something to put there.

Thoughts @jwchumley @PaulClark2 @LindsayYoung?

**Comment by LindsayYoung** [comment]
I think this circles back to creating different pages for different committee types. 

For committee types with independent expenditures, we could add the independent expenditures but candidate totals, like we have on the candidate pages. I think people would like that.

**Comment by jwchumley** [comment]
It definitely needs to have links to the expenditures. In the mean time the disbursements tab should go away I think.

**Comment by noahmanger** [comment]
On dev we now correctly show Independent Expenditures: https://fec-proxy.18f.gov/data/committee/C90015579/?cycle=2016&tab=summary

We already have issues for conditionally showing tabs and adding itemized IEs, so I'm closing this.
