### ISSUE TITLE
Feed of paper records processed

### ISSUE THREAD

**Issue by jsfenfen** [18F/FEC#14]
Paper records provided by Senate candidates / committees are OCR'ed by an outside vendor, and the data appears in several locations: data summaries are available in the webk file (which may have changed it's name, actually, but is the file that contains one line for every periodic report filed); the line itemization of contributions are available in the FTP bulk files; and the line itemizations of expenditures are available in a third location, and typically take even longer.  There's no way of knowing what data has been processed though, without checking every single file. 

What would be really helpful would be a feed of which paper reports have been added to which files. The webk files, for instance, are updated daily, so the summary of the paper reports are typically available at least a few days before the contribution line itemizations are (I think more typically this delay is weeks not days, but can't say for certain). I've never measured the timeline, but I think it's often months before the expenditures from paper records are available.

My best solution would be a json feed with link to original paper record, candidate+committee id, and description of what action had been taken. 

This is related to [issue 11](https://github.com/18F/FEC/issues/11)--and arguably the same--but I just wanted to highlight the special route that paper records take...

**Comment by LindsayYoung** [comment]
I am linking to this discussion and moving the task to the openFEC repo.
