### ISSUE TITLE
Seemingly many dupes of employer in the schedule_a 'by_employer' endpoint

### ISSUE THREAD

**Issue by corbyhobbs** [18F/FEC#142]
It's possible I'm accessing the endpoint in the wrong way, but if I'm not, it looks like there are many dupes of employer names in the '/committee/{committee_id}/schedules/schedule_a/by_employer/' endpoint even though hypothetically all these contributors should be grouped (I'm not counting obvious discrepancies like 'Google' vs. 'Google, Inc'). 

I tested out calling contributors to Hillary Clinton's principal campaign committee with this query: 

https://api.open.fec.gov/v1/committee/C00575795/schedules/schedule_a/by_employer/?sort=-total&cycle=2016&sort_nulls_large=true&per_page=100&api_key=DEMO_KEY 

and got back a total count of 17278 items. After calling all of these items, I saw that there are multiple entries for contributors that are spelled *exactly* the same way. For example, contributor summaries for 'THE BRYN MORGAN GROUP, INC' are repeated in their entirety five times within the call - two examples of which can be found here:

https://api.open.fec.gov/v1/committee/C00575795/schedules/schedule_a/by_employer/?sort=-total&cycle=2016&sort_nulls_large=true&page=10&per_page=100&api_key=DEMO_KEY

https://api.open.fec.gov/v1/committee/C00575795/schedules/schedule_a/by_employer/?sort=-total&cycle=2016&sort_nulls_large=true&page=13&per_page=100&api_key=DEMO_KEY

When I search specifically for that employer within Hillary's contributions however, I only get back one entry as expected:

https://api.open.fec.gov/v1/committee/C00575795/schedules/schedule_a/by_employer/?api_key=DEMO_KEY&employer=THE%20BRYN%20MORGAN%20GROUP%2C%20INC&sort=-total&page=1&sort_nulls_large=true&cycle=2016&per_page=20

After pulling all of Hillary's grouped employer data, I found that there were 3,372 rows that are duplicated exactly. When I deleted them I found I was much closer to her topline itemized contributions sum at ~$60K (topline figures say she received ~$63K). Without deleting these dupes, her total sum ends up at ~$70K.

Any idea what might be going on here?

**Comment by LindsayYoung** [comment]
Thank you for reporting! I will start looking into this now.

**Comment by LindsayYoung** [comment]
Still looking into this. 

Another weird thing is that this works:
https://api.open.fec.gov/v1/committee/C00575795/schedules/schedule_a/by_employer/?api_key=DEMO_KEY&employer=THE%20BRYN%20MORGAN%20GROUP%2C%20INC

**Comment by LindsayYoung** [comment]
Also, we only look at individual spending for occupational breakdowns. You can see the logic for that here: https://github.com/18F/openFEC/blob/develop/data/functions/individual.sql

**Comment by corbyhobbs** [comment]
Great to hear, thanks for the update! Keep up the great work.

On Tue, Nov 17, 2015 at 12:48 PM, Joshua Carp <notifications@github.com>
wrote:

> Thanks for catching this @corbyhobbs <https://github.com/corbyhobbs>. I
> took a look, and the issue is related to our sorting logic. When we sort on
> a field with many ties, results aren't guaranteed to appear in the same
> order, meaning that some results can appear on multiple pages. For now, you
> can get unique results if you take the sort option out of your query URL,
> but we'll aim to get this fixed for real soon. We're tracking progress at
> 18F/openFEC#1361 <https://github.com/18F/openFEC/issues/1361>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/FEC/issues/142#issuecomment-157501572>.
>



-- 


*Corby Hobbs* | Product Manager, InsideGov <http://insidegov.com/>
phone: 917.648.7562 | skype: corby.hobbs
www.graphiq.com | We're Hiring! <https://www.graphiq.com/careers>

**Comment by LindsayYoung** [comment]
OK, this fix went through a while ago, please reopen if you see any similar issues.
