### ISSUE TITLE
IE Matrix Filter Missing ;

### ISSUE THREAD

**Issue by patphongs** [18F/FEC#163]
Saw an error in my safari console for https://beta.fec.gov/data/static/styles/styles-f860a1b1.css

`.leaflet-oldie .leaflet-popup-tip` selector seems to be missing an ending semicolon for the last property in the Microsoft Matrix Filter

`.leaflet-oldie .leaflet-popup-tip {
width: 24px;
margin: 0 auto;
-ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)";
filter: progid: DXImageTransform.Microsoft.Matrix(M11=.70710678, M12=.70710678, M21=-.70710678, M22=.70710678)
}`

Not sure if it's related to this error I am also receiving with the CSS error: 

Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.

**Comment by noahmanger** [comment]
Sadly we have no control over this as it's an outside library we're using for the maps, but thanks for reporting! I'm going to close this.
