### ISSUE TITLE
2 -4 -6 issue

### ISSUE THREAD

**Issue by jwchumley** [18F/FEC#168]
https://fec-proxy.18f.gov/data/candidate/S2WI00219/?cycle=2016&election_full=false

Tammy Baldwin has no money if you choose full cycle (2013-2018) but has significant money if you choose 2015-2016 or 2013-2014. Also 2017-2018 option should probably either be grayed out or missing.

**Comment by jmcarp** [comment]
Fixed in the release tonight. Thanks for catching!
