### ISSUE TITLE
Upload FECFile as a repository; use github.com/fec

### ISSUE THREAD

**Issue by saizai** [18F/FEC#18]
1. Simple request: make the whole FECFile package open source. ;-)

2. Make a Github account for the FEC itself, for any code that's actually deployed (like the website, FECFile, etc).

**Comment by LindsayYoung** [comment]
I :heart: open source!

### repositories for this project:
- [FEC](https://github.com/18F/fec): a general discussion forum. We [compile feedback](https://github.com/18F/fec/issues) from betaFEC’s feedback widget here, and this is the best place to submit general feedback.
- [openFEC](https://github.com/18F/openfec): betaFEC’s API
- [openFEC-web-app](https://github.com/18f/openfec-web-app): the betaFEC web app for exploring campaign finance data
- [fec-style](https://github.com/18F/fec-style): shared styles and user interface components
- [fec-cms](https://github.com/18F/fec-cms): the content management system (CMS) for betaFEC
