### ISSUE TITLE
The Boy 

### ISSUE THREAD

**Issue by mehdi911** [18F/FEC#187]
Democracy has certain rules of interpretation for the proper understanding of all its legal and illegal instruments. These basic rules are established according to the nations understanding of democracy. Perhaps they are simple, common rules such that you, my reader, and I can understand and apply, without having to study the law. As our constitution holds that every American citizen has a right to form an opinion and propagate that opinion and to utilize all honorable means to make his opinion the prevailing one. Without this basic right, the liberty of an American citizen would be as insecure as that of a prisoner. Now take the constitution according to its plain reading and I defy the presentation of a single anti- human fealty clause in it that is the Leviathan notion of a social contract between people and power. We cannot pass through an hour without noticing the Leviathan notion while majorities of the world’s 6.5 billion people are left behind in the name of democracy in many confused countries.

Democracy had become a boy who had no home. His parents are dead and his country would not care for him due to his pigment. In order to survive he made a bower of branches for an abiding place and hunted for food. He had no clothing and that showed him as being very ragged and dirty. When privileged members of democracy passed by holding their noses he noted the jealousies from the good looking faces and decided to go away from his tormentors and become a great hunter. One night he found a canoe. He had never seen this canoe before so he jumped in it. Stepping in he grasped the paddle and pushed. Suddenly, the canoe shot into the air and he paddled above the clouds and under the moon. For a long time he went eastward and soon the canoe dropped into a river and then the boy paddled for the shore.
On this side of the river there was a great cliff that had a colorful face which looked like a man. It was at the fork of the river where this cliff stood. The boy decided to make his home on the top of the cliff so he climbed it and built a cabin. The first night there was a full moon and while he sat on the edge of the cliff he heard a voice saying ‘give me some water.’
Looking around the boy seeing no one replied ‘Why should I give you water?’

There was no answer and the boy began to fix his arrows for the next morning hunt.
After a while the voice spoke again ‘Give me some water’ and the boy took some water and threw it over the cliff the voice said ‘Now I’ll tell you a story.’
Feeling happy awaited the boy listened to a story that seemed to come directly out from tress on the cliff. Finally the voice paused because story had ended. Then it spoke again saying it shall be the custom hereafter to present me with a small gift for my stories. So the boy gave the trees more water for another story.
The next morning the boy hunted and caught a great number of fishes and birds for food. He made soup and smoked the fish. The smell of the smoked fish went far into the valley and an old man who was hungry followed the smell and came to the boy for food. First the boy was scared of the old man who were a white yamaka ( white hate) but then realized that the old man is hungry and wanted to eat so the boy offer him seven small smoked fishes and a bowl of soup. The old man said to the boy I have nothing to offer you but my blessing with my yamaka ( white hate) and a rosary to remember me. The old man left the cliff after eating the food .
The boy puts the yamaka (white hate ) on his head and put the rosary around his neck to look cool. Suddenly the voice came from the cliff ‘where is my Sadiqa ( gift)’ so the boy threw a few bowls of water toward the direction from where the voice was coming perhaps the voice started and said, hereafter when I speak announcing that I shall tell a story you must use the rosary beads by saying ” Rab-e-zidni-Ilma ” in your heart so I may know you are listening you must never fall asleep when feel dizzy you must say louder these words.’ Afterword you will give me presents and I shall be satisfied from your Sadiqa ( gift) The next morning the boy felt better and energetic as he hunted great many fishes and a deer for food.

He skinned the deer and saved the skin that evening he was tired fallow sleep got up early morning he sat on the rock next to his cabin and looked at the sunrises from the East. He wondered if his friend would speak again and while thinking he started chipping some new arrows points. Suddenly as his train of thought changed, he heard the voice ‘Give me some food not water’ now the boy threw few hunted birds and a fish into the trees.
The story begins long into the night one wonderful tale after another flowed from the trees. The boy falling asleep by listening to the story, the next morning boy hunted far to the East and found a small village. No one knew him but they liked his yamaka (white hate). He soon found many friends. There were some hunters who offered to teach him how to hunt big game, and they went with him to his own camp on the cliff. At night he allowed them to listen to the stories that came from the trees but he was the only one who could speak to the trees and stories began when the boy was present at the cliff. Therefore, the boy had many friends with him to hunt and spent time to gain knowledge.

He kept giving water and food to the trees to gain knowledge through stories. One day he made a new suit from the deer skin and desired to obtain decorated leather. Therefor he went to the village and found one house were a young girl lived with her parents who saw suited for work . As soon as he knocked on the door the girl spoke up and said ‘here is your leather strips to finish suit. I have been waiting for you to come for them.’ The mother spoke saying ‘I now perceive that my future son-in-law has passed thought the door and is here.’ The boy was surprised, thought he was dreaming and punched himself. Thereafter the young lady brought bread and cup of water and asked ‘my mother greatly desires that you should marry me.’ The boy looked at the girl and very satisfied ate the bread and drinks water.

The boy stayed at the house and married the girl. Perhaps a few villagers were jealous from his yamaka (white hate) that represented knowledge and because the young man married the most beautiful girl from that village. They acted in an evil manner towards the young man and one night the bride said to her husband ‘we must go away from here the villagers will kill you because you have different religion and pigment.’ The young bride and groom arose on the cliff. Soon the trees spoke began to relate wonder stories of things that happened in the old days. The bride was not surprised and said this same sound told my parents about you should appear to get leather strips and marry your daughter to him.
The young man was surprised thanks to the voice that came from trees for beautiful wife. All winter long the young couple stayed in the cabin on the cliff and heard all the wonder tales of human history. The young boys brain was full of stories with a lot of knowledge. As springtime came the bride said we must now go east to your own people and you should become a great man. Perhaps the boy was sad and said well in my own country am an outcast and called by many names. The bride laughed saying nevertheless we should go east. They collected few important items the young couple seated themselves into the canoe and reached east. Together they walked to the village wearing nice clothing looking handsome people from village came out to see new couple. The boy told villagers that am the boy whom you once were accustomed to call outcast, aborted child, I have now returned.’ Every night all villagers gathered around him to listen to the stories. The couple had four children and busy with the villagers every evening they all came to a place called Jamee-Aluum to listen to stories of nature. The boy never forgot the Sidque (gift) for the tress on the cliff.

The boy was 40 years old now and one Friday he asked the voice what is Sound?
Suddenly he smelled Egyptian mist around him and then a smelled of fresh bread coming out from oven the voice came that the sound travel through the wave like this smell. That night the boy told a story of people who try to control population of an ancient history by abortion and wars by assuming they are the protector of nature to control humanity and died from the sound that was extremely loud. at the end of the story Kids clapping and dancing.

A voice came that am alive from the sound of Gogroos (musical instrument) from the angles of life who are sending gusts of smiles on innocent children’s for democracy.

Written by Ajmal Mehdi
The People Party of Connecticut 
Happy New Year 2016

**Comment by jenniferthibault** [comment]
Thanks for the story. Closing out since there's no beta.fec.gov feedback to address.
