### ISSUE TITLE
Tagging Contributions and Expenses by Congressional District as well as State, Unambiguously

### ISSUE THREAD

**Issue by adamclayman** [18F/FEC#21]
Are donor and expense addresses already geocoded by the FEC and individually cross-matched to federal Senate and House Districts? If so, I have not found any clear sign of it. In the CVS exports of expenses and contributions, I can only see "City, State, ZIP". That doesn't match up precisely with Congressional Districts.

I would find it very hard to believe that Google, Microsoft, and other big players would not gladly geocode all that data for you for free, as part of their public service mission. To get permission for unlimited geocoding by the 18F for the purposes of geocoding and disambiguating FEC contribs and expenses to Senate and House Districts, I would urge you to get in touch with the Social Impact Team at Google. Anthea Watson-Strong (@antheaws) is awesome, and she's available and very responsive via Twitter. I'll try to patch her into this conversation. If she and her team can't get you access to 100,000 geocode requests per day (forward or reverse) on their own, I am sure she will know with whom you ought to be talking to get that clearance. It's the sort of thing that I doubt the Google Team would think twice about. With each contribution and expense tagged by State (which is also Senate) and House District, more important views of the data become readily accessible for end-users in a variety of organizations, and we can just pull the Congressional District and State tags rather than doing the work of geocoding and interpreting that ourselves. I would also suggest that this is well within the statutory authority of the FEC (to collect addresses on contributions and expenses and associate them with a State and Congressional District of origin) and would prove very useful for candidates who want to self-monitor their own election campaign's contribution sources, so that any funds they use remain tied to their Congressional District.

This conversation was started in a different ticket — for the start of this conversation, and an extended exchange with @dwillis and @jsfenfen, check out https://github.com/18F/FEC/issues/20.

This geocoding request is applicable most of all to the House Races rather than the Senate, since Senate contributions and expenses are already tied to the appropriate state — with State matching 1:1 with Senate electoral districts — in the publicly accessible data sets.

**Comment by LindsayYoung** [comment]
Thanks for the great discussion on this thread!
