### ISSUE TITLE
Standardize Presentation of Commissioner Contact Information

### ISSUE THREAD

**Issue by adamclayman** [18F/FEC#22]
If you check out the FEC Commissioners Members Page (http://www.fec.gov/members/members.shtml), you might notice that Commissioner Goodman has no contact information publicly listed at all, and the display formats given for C. Walther and C. Petersen are so different in schema from that of C. Ravel and C. Weintraub so as to make C. Walther's and C. Petersen's contact information almost unnoticeable to a quick citizen scan. 

Any effort to standardize the listed contact info in a similar bubble will help prevent anyone from leaving the FEC Site under the impression that Commissioner Goodman is unreachable, or that Commissioner Walther and Commissioner Petersen (who post contact information, just in a different format) are too.

**Comment by nerodain** [comment]
![genderjourney3_20_1_](https://cloud.githubusercontent.com/assets/11280633/10003318/a4e57f12-6060-11e5-8582-6e583b8e38b3.jpg)
![150301_club_for_growth_ap_1160x629](https://cloud.githubusercontent.com/assets/11280633/10003323/aa35b4b4-6060-11e5-9e88-12f923c9c7f7.jpg)

**Comment by nerodain** [comment]
www.thetransgendercenter.com website register/commonwealth of va 211586771/adminstration/agent/consitution rits[1997][1996][1994][19]VHDA HOUSING DISCRIMINATION COMPLAINT CASE 4011237 FEDERAL REGULATION DIMINION ACCOUNT 0449853597/COUNTY OF HENICO ACCOUNT 0035951-00269227/DMV COURT FINES A64206275 URGENT REQUEST ATTENTION [8047287706]

**Comment by jenniferthibault** [comment]
Thanks for this feedback! As we get closer to building out these pages of the [beta site](https://beta.fec.gov/) this is a great point to have written out explicitly.

**Comment by noahmanger** [comment]
New commissioner pages are live with new, consistent templates and contact info https://beta.fec.gov/about/leadership-and-structure/commissioners/
