### ISSUE TITLE
Real Simple URLs for FEC Candidate and Campaign Pages (URLs We Can Share)

### ISSUE THREAD

**Issue by adamclayman** [18F/FEC#23]
When I'm using the map to navigate to the federal candidate campaign finance viewer, the URL doesn't update in the address bar, so I can't copy and paste the link from my browser to directly link a second- or third-party to a given FEC page.

The only link I ever have in the address bar is this one:
http://fec.gov/disclosurehs/HSCandDetail.do

That's completely inscrutable! It violates almost all the rules for a good unique resource locator and greatly limits the ability for persons to navigate any part of this (name)space.

I think the public ought to be able to send someone to any and/or all of the following meaningful addresses, or a similar URL schema you design:
http://fec.gov/disclosure/ohio
http://fec.gov/disclosure/house/oh-11/
http://fec.gov/disclosure/house/oh-14/
http://fec.gov/disclosure/senate/oh/  [goes to -> disambiguation by cycle]
http://fec.gov/disclosure/senate/oh/02012 * [Citizen Fisher + Citizen Portman, Historical]
http://fec.gov/disclosure/senate/oh/02012 * [Citizen Mandel + Citizen Brown, Historical]
http://fec.gov/disclosure/senate/oh/02016 * [Citizen Portman + Challenger, Accumulating Funds]
http://fec.gov/disclosure/senate/oh/02018 * [Citizen Brown + Challenger, Accumulating Funds]
http://fec.gov/disclosure/usa/ [goes to -> disambiguation page, Map + Presidential Race]
etc. 

You could even drop the "/disclosure/" term to make these URLs even more easily sharable. It doesn't need to be there, and it makes it harder for someone to sketch out the URL they want someone to visit on a napkin.

All these pages already exist — they're just seemingly impossible to directly access from the address bar, and the URL schema can be so much simpler to share from point-to-point.

RE: 0201X dates above... I like Institute of the Long Now dating, because they help remind me of 7th generation obligations, but I know of course that you'll need to drop the leading 0 on dates for publlic accessibility.

[Also, if this is covered elsewhere as a ticket, please do feel free to close this one as done. :-)]

**Comment by citizencontact** [comment]
Thanks Adam for an excellent and crucial point. In years past not only were the URLs not helpful, many were on the dotcom site of the contractor and not in the dotgov TLD. I have added a similar issue, but to add elections as URLs. This will allow a binding of all the candidates running in a particular election. see: https://github.com/18F/FEC/issues/36

**Comment by LindsayYoung** [comment]
Happy to announce we do have stable links for the resources that you mentioned. 

The pattern for candidates:
https://beta.fec.gov/data/candidate/<fec_id>

The pattern for a candidate in a particular cycle:
https://beta.fec.gov/data/candidate/<fec_id>/?cycle=2012

The pattern for committees and other filers:
https://beta.fec.gov/data/committee/<fec_committee_id>

The pattern for committees and other filers in a particular cycle:
https://beta.fec.gov/data/committee/<fec_committee_id>/?cycle=2012

The pattern for House elections:
https://beta.fec.gov/data/elections/house/<state>/<district>/<year>

The pattern for Senate elections:
https://beta.fec.gov/data/elections/senate/<state>/<year>
