### ISSUE TITLE
open thread: examples of using our API

### ISSUE THREAD

**Issue by leahbannon** [18F/FEC#247]
* Library of Congress is using it to collect the web addresses for their work archiving campaign websites.
*

**Comment by noahmanger** [comment]
@leahbannon do you still want to do this or can we close this issue?

**Comment by leahbannon** [comment]
Maybe I could find a better spot to keep a running list of examples of uses of our API that doesn't get in your way? Like in the new wiki structure?

**Comment by noahmanger** [comment]
Sounds good.
