### ISSUE TITLE
add tooltip help and wayfinding

### ISSUE THREAD

**Issue by johnnyporkchops** [18F/FEC#25]
This could include adding basic tool tips popups to define terms or application choices, or follow-along help functionality that steps the user through certain processes.

**Comment by jenniferthibault** [comment]
This has been implemented in a few instances, and we are building out systems of when to use tooltips and when information can be explained directly on the page. 

For example: 
https://github.com/18F/openFEC-web-app/pull/717
https://github.com/18F/openFEC-web-app/pull/838

I'm going to close this in favor of tracking specific instances for tooltips in the future.
