### ISSUE TITLE
Searching Advisory Opinions

### ISSUE THREAD

**Issue by CletaMitchell** [18F/FEC#27]
The FEC sends emails re: updates re: Advisory Opinions.  When you click through to see what it is, the link takes you to the search page.  So unless you actually wrote down the number of the AO or AOR which is the subject of the email, you have to go back, look it up, and then go search for it.  The search engine to FIND / research advisory opinions is so much more difficult than before it was 'improved' several years ago.   It is almost impossible to find advisory opinions even when I know there have been opinions on that subject.  So the entire search process for advisory opinion research needs to be completely overhauled -- the links that the FEC sends out about updated AO information should take the user directly TO the subject of the email without having to go through a search -- just link to it for pete's sake.  Then, a complete overhaul of the search engine for finding AO's needs to be undertaken -- go back and look at what was discarded when it was 'updated' a few years back. THis is so much worse than it used to be.  Finally, it is not possible to read AO's search for on an iPad.  It is impossible to navigate on newer devices supported by other systems such as research on an iPad.  This is a very clunky and not user friendly system.  It was better before it was 'fixed' so I've yearned for the old system.  It was so much easier.

**Comment by CletaMitchell** [comment]
The search terms are just very limited – so it is really hard to try to read the mind of the search engine to come up with the right search terms to find things that I know are there.  Hard to describe in the abstract, though

Cleta Mitchell, Esq.
Foley & Lardner, LLP
3000 K Street NW #600
Washington, DC 20007
(202) 295-4081 (direct)
(202) 431-1950 (cell)
(202) 672-5399 (fax)
cmitchell@foley.com

**Comment by noahmanger** [comment]
Going through old issues and just wanted to follow up that we now have a new and improved (and still constantly improving) AO search on the beta site https://beta.fec.gov/data/legal/advisory-opinions/ . AOs are now permalinkable, so I'm closing this issue, but happy to field additional comments.
