### ISSUE TITLE
Searching IE and EC reporting

### ISSUE THREAD

**Issue by CletaMitchell** [18F/FEC#28]
there should be a way to search using different mechanisms -- by date, by candidate, by spender....and to easily slice and dice -- it is really hard now to do anything except scroll through by date - rather than just being able to search by race / candidate (who is spending what against / for this candidate) or by group -- it is really clunky to try and quickly look at / generate a report that shows who is spending what for or against this candidate or in this state - or how much this group has spent in a certain time period.  It ought to be much more easily searchable than it is now.

**Comment by LindsayYoung** [comment]
We are happy to say that we have independent expenditures by election on beta.fec.gov:
https://beta.fec.gov/data/elections/president/2016/?tab=spending

We are planning at some point to have an independent expenditure browse view, and adding independent expenditures in on committee pages that makes them more easy to discover as well. 

Thanks for writing in!
