### ISSUE TITLE
Redesign it

### ISSUE THREAD

**Issue by beanlovin** [18F/FEC#30]
Its on the left! Modern web design is responsive with scaling properties. If you cant afford it ill do it myself!

**Comment by LindsayYoung** [comment]
Great point! You will be pleased to learn we are making progress toward a beta site. If you want to take a peek at what we have so far, it is an open-source project on GitHub [18f/openFEC](https://github.com/18F/openFEC).

**Comment by noahmanger** [comment]
We've done this! https://beta.fec.gov.
