### ISSUE TITLE
Add single endpoint that outputs last .fec filing number

### ISSUE THREAD

**Issue by saizai** [18F/FEC#31]
For polling use, it would be helpful to have a single URL that just returns the maximum / most recent .fec ID number for regular and senate filings respectively (as in `http://docquery.fec.gov/dcdev/posted/#{filing_id}.fec` and `http://docquery.fec.gov/senate/posted/#{filing_id}.fec`).

**Comment by dwillis** [comment]
+1 to this or something like this.

**Comment by LindsayYoung** [comment]
Thanks! I noted this in [# 521](https://github.com/18F/openFEC/issues/521) in the OpenFEC repo, where we are keeping track of development tasks.

**Comment by LindsayYoung** [comment]
Moving this conversation to 18F/openFEC#1355
