### ISSUE TITLE
$5,200 or $5,400 limit for couple?

### ISSUE THREAD

**Issue by pgra** [18F/FEC#32]
On WWW.fec.gov/pages/brochures/citizens.shtml it says $2,700 limit for individual contrib but lower down it says under Contributions from Family Members .....For example a couple may contribute a $5,200 check........ I think this should be $5,400, which is 2X$2,700.           Yours truly, pgra (pgra@email.com)

**Comment by saizai** [comment]
The individual limit was $2600 before. Seems like it's a failure to update
fully.

**Comment by rjmajma** [comment]
Hey PGRA, thanks for bringing this up. I believe the FEC spotted the problem and has fixed it. Check out the change made here: http://www.fec.gov/pages/brochures/citizens.shtml.

Thanks!
