### ISSUE TITLE
Minor Political Parties are Systematicly Discouraged and kept in Finanicial Problems 

### ISSUE THREAD

**Issue by mehdi511** [18F/FEC#33]
Minor political parties and systematic discouragement 

The political and social revolution begins when innocent people suffer from the Republican and Democratic policies of the Patriot Act which was made for minorities and the People Party members in an attempt to keep them in financial hardship many minor political parties are discouraged by local news media and press by not covering political and social events in local libraries or even publishing political opinion and letters. American minorities are discouraged not to take active part in political process which has been dividing America , our business shut down, house boarded up just because we believe in change. We would request freedom of the press and equal opportunities for all Americans for better future .

Sincerely,
A Mehdi 
The People Party of Connecticut
507 Pine Street 
511 Pine Street
Forestville CT 06010
860.583.3338 
IN GOD WE TRUST WE HAVE FAITH IN HUMANITY 

Sent from The People Party www.humanfealty.com
The People Party is a Minor Political party in the Constitution State of Connecticut for domestic tranquility.

**Comment by saizai** [comment]
This isn't really a place that can address your concerns. It's about the
FEC's website, not FEC policies, and even those can't really change whom
the media pays attention to.

If you have an actual proposal for changing FEC regulations in some way, 11
CFR 200.2 tells you how to go about asking the FEC to do so. In any case,
this isn't it; we're coders, not FEC Commissioners. ;-)

**Comment by jenniferthibault** [comment]
Thank you for your feedback. Our current focus is on redesigning the website and making the data and other resources available there easier for the public to access and understand. I'm going to close this issue for now — please contact the FEC directly with any policy feedback.
