### ISSUE TITLE
Mega Menu Profiles Search

### ISSUE THREAD

**Issue by patphongs** [18F/FEC#334]
Mega menu search under Profiles only allows users to search by candidate, but not by committees, as indicated.
<img width="365" alt="screen shot 2016-05-25 at 6 25 38 pm" src="https://cloud.githubusercontent.com/assets/12799132/15558194/4b7c1022-22a6-11e6-8003-f1f20adc8e85.png">

**Comment by emileighoutlaw** [comment]
Ahhh, that filler text should also probably just say `Search`, otherwise it's weirdly repetitive

**Comment by LindsayYoung** [comment]
Chiming in as one data point- I would like this to search candidates and committees, like we had at one point, or candidates or committees like you can on the data landing page.

**Comment by jenniferthibault** [comment]
Aw rats, I just filed a duplicate issue: https://github.com/18F/openFEC-web-app/issues/1238.

Good eyes, everyone!

**Comment by noahmanger** [comment]
Thanks for catching @patphongs ! Closing in favor of Jen's issue.
