### ISSUE TITLE
Freedom for The People Party of Connecticut 

### ISSUE THREAD

**Issue by mehdi511** [18F/FEC#34]
DEMOCRACY : The legislative and executive power in any democracy of the world has right to direct how force of democracy should be employed for preserving the community and members of the branches.

The matter of The Patriot Act is that it exempts themselves from obedience to the laws they make in both its making and executing to their own private advantage. Thus to me this is the end of Democracy. Therefore a question arises that in a well ordered democracy where the good of the whole society is so considered as it ought, the legislative power is put into the hands of diverse minorities who suffer from the law.
 
In any democratic society laws are ought to be designed for the good of all citizens. Such as raising the taxes of property or eminent domain laws with the consent of the Citizens. 
 
The fundamental law of nature that represents Freedom or free will is based on Democratic values. God or nature never allows a man to abandon himself. Human Beings are not allowed to take their own life neither this power given to State legislative or executive powers. 
 
Then why is The Patriot Act in a democratic society. Thus, innocent people have no other remedy in this law as in many other laws of this new American Democracy. 
 
The fundamental law of nature has thought man that where they have no Judge on earth or justice in democratic society then appeal to heaven for the rulers in such matter for injustice. 
 
By reading and understanding the new rules of American Republicans and Democrats legislative and executive power this is absolute monarchies here as well as other governments who copycat our laws. 
 
Sometime I wondered, God having made Man with such an intelligent mind that in his own judgment it was not good for him to suffer and live in society, with different languages, cultures , family , justice and freedom of free well. We would request FEC to help minor political Idealogies for Change and different America that stand for Freedom and justice .
Sincerely, 
A Mehdi 
The People Party of Connecticut
www.Americansparty.com

**Comment by mehdi511** [comment]
VE RI TAS

VE RI TAS IS THE SPIRIT OF DEMOCRACY

As we observe this new world democracy stirring years of war and promises of change with peace, proved to be the most tremendous failure of our time. Democracy is a law used to produce fruit of knowledge. Knowledge uplifts freedom and liberty with basic rules of life in a democratic family, city, society, state or country. The best democratic societies have minimum laws for basic safety of its people. Perhaps the peoples decisions is a democracy based on the numbers of votes to make a law and by selecting wise minds for office.

My main concern is that many governments, a select few individuals, make decisions daily while the Constitution of democracy is according to the people. The law that is pure and truth goes by the name VE RE TAS. The past thirty years the purity and truth of democracy digested greed and lies into the system which is producing difficulties.

Special conditions and tragedies are created from the influence of very narrow interest groups who are gaining authorities. Such institutional democracy raises many questions and concerns of future to remain comfortable. What must be done to secure a democracy and justice?

VE RE TAS the truth by eliminating entitlements. Reform by changing democracy into new design of human fealty. It is a universal desire to uplift human being by changing the machinery of infidels. Smaller government principles can create overwhelming waves of inventions by fixing dysfunctional part of democracy and privatization of responsibilities.

By 2050 technology will play a bigger and better roll in management of civilizations with economic performance between many nations. We have the extremely difficult challenges as well as advantages to unite all diversities to one identity of America while China has just Chinese and India with Indians as well as many others without much diversity. Cultivation of ideologies brings the most advance knowledge to self is Sine qua non to democracy.

The last 12 years, war overburdened democracy into selfishness of special interest groups of warmongers. We were pushed in this mess to divert attention by very smart minds that have no face. Enemy, which has a face, is better than the friend who is faceless. It’s getting costly with money and most important image. In order to reaching far into the future certain things must change. Our foreign policy and Immigration balance is extremely important by diversifying with different cultures for universal aspiration and human fealty.

Certain basic laws of freedom needed to be re- written and reinstated in the terms of ethnological ideologies. Welcoming new ideas for faster services, and by the teachings Nathan Hale who once said, I only regret that I have but one life to lose for my country.

Sincerely,  The People Party.﻿

IN GOD WE TRUST WE HAVE FAITH IN HUMAN FEALTY

**Comment by jenniferthibault** [comment]
Thank you for your feedback. Our current focus is on redesigning the website and making the data and other resources available there easier for the public to access and understand. I'm going to close this issue for now — please contact the FEC directly with any policy feedback.
