### ISSUE TITLE
Illegal Legislation and Serious Threats 

### ISSUE THREAD

**Issue by mehdi511** [18F/FEC#35]
Minorities like us, which is less than 1 % in the United States, continue to face serious threats, discrimination and racism, and are frequently excluded from taking part fully in the economic, political and social life. Today, we face new challenges, including legislation, policies and practices that may unjustly impede or even violate our rights by taking our Proprties, closing our Bussiness and keeping pressure and problems so we would give up our dream to change America for Freedom and Human Rights. 
The People Party of Connecticut 
www.humanfealty.com

**Comment by mehdi511** [comment]
FOR THE PEOPLE BY THE PEOPLE 

Is is true that the two-party system is responsible for the deficit and American middle class vanishing by showing change for the worse?

The idea of this new and advanced America is nice as long as we can change the mental status of all who ignore minorities and minor political parties. The struggle in today’s fusion societies for modernity by ignoring change and new ideological matter can be very costly for all of us and for the environment. Modernity in cultures where the two-party system is deeply connected to the American way of life is getting old unless we change their mentality for new directions. The conflict of choice can be cured by teaching young kids that when the brain is premature, they should be independent and honest from corporate influence who control major political parties and rules.

The trend of the vicious circle which is trapping future generations into a long and dangerous struggle of new fusion world by assuming that the key to modernity is changing color of leadership will not divert the American ship of democracy towards the shore of true democracy. In any democracy it’s ok to construct big and tall buildings, highways, malls, cities, industry, automated machinery and nuclear, solar, fuel cell fusion power plants as long as we educate future generations according to time. The key modernity is knowledge with the balance of nature.

The problem that we see is that the majority of people who control major political parties in America are from that 10 percent circle of higher educational institutes who do not realize the reality of Main Street or common Americans. They create very young and energetic educated leaders who are unskilled, unqualified and illiterate about the poor and middle class America but they have money with media to rule.

Once they are in the system they need to appoint judges, justices and contributors to improve the ladder to make a dynasty for the future. The country gets by one way or other as we see because it must while they live a good life comfortably with full benefits. As soon as the second party successors grow up within eight years are ready with same road to the White House. The result of this is that after every 20 or 25 years, country and people go back to the starting point again; this vicious circle and helplessness continues because the new generation of victors have the same ideologies that the past did.

In order to stop this vicious circle, we the people must educate and change old ideologies of two-party politics in order to divert the ship of our democracy which is for the people by the people.
The People Party of Connecticut
511 Pine Street Bristol CT 06010

**Comment by mehdi511** [comment]
Fair Competition 

Since 1776 it seems Republicans and Democrats are living in a fantasy Political system, they pre arrange elections without respecting the Constitution and federal , state and city charters. In 21st Century every one is equal and there is no such thing as competition of ideologies as long as two parities rule continues . It is true doesn't it since the founding fathers of American democracy.  Well now it doesn't work.
In order to advances the human civilizations fair competition helps grow people knowledge and laws enormously in a true democratic system. 
If there was no competition we Americans would have been living in Stone Age and would never landed on the moon. The competition becomes the national pride for people in order to grow but it must be fair and clean . 
2012 Election the people party of Connecticut received 841 votes as an independent voter registrar and came on third position according to federal rules and hundreds of democratic city around the world whom populations in more then sixty thousand people. 
As an Upright Americans we owe much of our advancement to mini competition and revolutions every now and then between ideologies, companies, nations , technology as well as system of democracy and Human fealty. 
This is competition of ideas and technology that brought us to a new high and President Obama in the White House. 
Our political structure and system needs an honest competition with trust and we the members of The People Party and myself challenges The Republicans and Democratic leadership to give us opportunity to challenge there ideological principle by respecting 2012 Election outcome in which People Party won a seat in the voter registrar office to organize for next Competition. 
Written by Ajmal Mehdi
The People Party 
www. Americansparty. com

**Comment by jenniferthibault** [comment]
Thank you for your feedback. Our current focus is on redesigning the website and making the data and other resources available there easier for the public to access and understand. I'm going to close this issue for now — please contact the FEC directly with any policy feedback.
