### ISSUE TITLE
Feedback on receipts page

### ISSUE THREAD

**Issue by noahmanger** [18F/FEC#369]
A couple things to log here from recent feedback shared off Github:

- The recipient name is cut off
![image](https://cloud.githubusercontent.com/assets/1696495/16251392/6c691ee4-37da-11e6-80c9-1284d7136ba5.png)

- Request to include the link to the file in the table itself
![image](https://cloud.githubusercontent.com/assets/1696495/16251395/71949c86-37da-11e6-8d0a-4962fdcace32.png)

**Comment by jenniferthibault** [comment]
Made a bit of progress on this with the last release: contributor names are no longer cut off!

**Comment by jenniferthibault** [comment]
Closed by https://github.com/18F/openFEC-web-app/issues/1304
