### ISSUE TITLE
User-specific format needed

### ISSUE THREAD

**Issue by andrewudstraw** [18F/FEC#37]
My name is attorney Andrew Straw and I have worked on court record reform in both Virginia and Indiana.  When I worked on the Indiana Supreme Court's new website, I suggested that the Court use a user-oriented format.  This made the entire Indiana Supreme Court website easier to navigate, with less wading through irrelevant material and links.

Note how the Court has the categories I came up with at the top:

http://www.in.gov/judiciary/supreme/?vm=r

If I were advising the Court today, I would suggest that they make the font bigger and compliant with the ADA in every way.

The first thing I would recommend to the FEC, therefore, is to reorganize the information on your website so that it allows different types of common users to find the information they need easily.  These categories need to be there:

Candidates (President, Senate, House)
Attorneys
Treasurers
Public
Students
Data/Search
Press

Each of these should have its own FAQ and FEC staff contacts, with both fax and email.
Every type of user should be able to have an account.  Public and Press accounts should have the ability to track different candidates and their filings, with notifications.  There are so many ways to provide outstanding services by user type.

If there needs to be some cross-referencing within each of these categories, that is perfectly fine.

When someone comes to your site, they should see very clearly a category that describes why they are visiting.  They should not have to sift through lots of links and URLs to find what they are looking for.

Also, there needs to be an online chat assigned to each type of visitor.  Many private businesses and government offices have this, and having a chat service makes the entire site 100% friendlier to use.  People should not be required to call to get information, but calling should be an option.  The chat service should go from 9am to 10pm EST M-F, and from 1pm-8pm on Saturdays and Sundays.

You should outsource part of the chat service.  You should offer the chat in several languages, including English, Spanish, French, Russian, Chinese, and Arabic.  Every chat operator should be native in the language in which they are providing the service, and fluent in English also.

Thank you for the opportunity to comment.  If you would like to contact me, my email is andrew@andrewstraw.com

Sincerely,

Andrew Straw
www.andrewstraw.com

**Comment by saizai** [comment]
Just re. accessibility: I'd remind 18F to take a read of Section 508 of the
Rehabilitation Act, 36 CFR 1194.22, and particularly ATBCB-2015-0002 (which
is much more detailed).

I don't know if font size needs to be bigger per se — users can control
that, if it's not baked into an image — but it should definitely be fully
accessible, and be oriented towards actual users' use cases (in order of
their commonness) rather than just reflecting internal FEC organizational
structure.

**Comment by andrewudstraw** [comment]
Very good advice to check those out.

The U.S. Access Board is the place to look, since they are the agency tasked with designing the standards.

http://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-section-508-standards/guide-to-the-section-508-standards

**Comment by LindsayYoung** [comment]
Thanks for your comments @andrewudstraw There are a lot of good ideas here. 

You will be pleased to hear that we are building the site with different users and doing repeated usability testing with different kinds of users as the site progresses. The site will be 508 complaint as well.
