### ISSUE TITLE
Request: Provide context for what is included in the data tables

### ISSUE THREAD

**Issue by noahmanger** [18F/FEC#370]
Another comment shared offline: 

![image](https://cloud.githubusercontent.com/assets/1696495/16251498/5c31a946-37db-11e6-8445-7d5d0f872ccd.png)

I think this raises an interesting question about if we want to bring in the "About this data" pattern from the overviews to the data table pages.

**Comment by jenniferthibault** [comment]
Issue moved to [18F/openFEC-web-app #1322](https://github.com/18F/openFEC-web-app/issues/1322) via [**ZenHub**](https://www.zenhub.com/)
