### ISSUE TITLE
District Data

### ISSUE THREAD

**Issue by andrewudstraw** [18F/FEC#38]
Each district across the country has specific additional requirements imposed beyond the Article I, section 2 requirements.  E.g., petition signatures.  These should be listed under the candidate's information and in a data section of the site.  

Also, the FEC should obtain voter information from each whole state and provide this to each person who registers as a candidate for federal office.

The FEC should obtain voter contact info, including email address, for each state, for federal candidates.

The FEC should create an official petitioning system that all federal candidates can use to be put on the ballot.  This system should have an iPhone app associated.

Every voter should be allowed to set up an account and interact with candidates.  Voter status should be verified against the data from the states.  This encouragement of 1st Amendment activity is very appropriate.

Again, thank you for the opportunity to make suggestions.

Andrew Straw
www.andrewstraw.com

**Comment by LindsayYoung** [comment]
It is the states, not the FEC that run elections, so the FEC doesn't have the proper mandate to add petitions to ballots or collect voter information. 

Thank you again for taking your time to comment.

**Comment by andrewudstraw** [comment]
whatever it can do under its mandate, it should do. I think the states have way overstepped the idea of conducting elections, and instead are adding new requirements to federal office.  I think adding new requirements beyond what the Constitution requires gives the federal government the ability to regulate that. I, for instance, broke both of my legs and my pelvis in a car accident and it hurts me to stand or walk for a long time collecting signatures.

I think it's crazy that states are allowed just put new requirements.

The FEC has many opportunities to provide services both candidates and to the public.  go to town! Every time you offer an easy service to use, it makes it easier for people to understand the process and be involved.



Andrew Straw
______________________
Andrew U. D. Straw
Attorney at Law, admitted to practice in: 
U.S. District Courts:
Northern District of Illinois
Northern District of Indiana
Southern District of Indiana
U.S. Court of Appeals for the Fourth Circuit
Indiana Supreme Court, 6/7/2002
Virginia State Bar: Inactive Associate Member in Good Standing.  Admitted 6/7/1999
 
1900 E. Golf Road, Suite 950A
Schaumburg, IL 60173
(312) 985-7333 (T)
(877) 310-9097 (F)
andrew@andrewstraw.com
www.andrewstraw.com

Compilation of my recent disability access work:
www.accessviolations.com
 
The information transmitted in this e-mail message and any accompanying attachments are confidential and protected by legal privilege. The content contained herein is intended only for the use of the individual(s) named above. The distribution, copying, disclosure or other use of this e-mail by unauthorized persons is prohibited. If you have received this transmission in error, immediately notify the sender or Andrew Straw, Esq. and permanently delete this transmission from your system, including attachments. Thank you for your cooperation.

Any campaigning messages are Authorized by the Committee Andrew Straw for Congress.
