### ISSUE TITLE
Complaints

### ISSUE THREAD

**Issue by andrewudstraw** [18F/FEC#39]
If a citizen wishes to report a violation of a law or regulation, the Public part of the site should provide a web form to do so.

**Comment by andrewudstraw** [comment]
It should send a copy of the complaint via email to the citizen with a time stamp.

**Comment by noahmanger** [comment]
Thanks for taking the time to comment. Our understanding is that complaints have to be filed via paper, but we'll definitely keep this in mind when we start working on the complaint section of the website.
