### ISSUE TITLE
Form F3X (ver 8.1) data description ambiguous

### ISSUE THREAD

**Issue by roberthadow** [18F/FEC#3932]
Data lines with FORM_TYPE = F3X (ver 8.1) are described at http://www.fec.gov/elecfil/eFilingFormats.zip which describes the same data multiple times. For example:
**19. Total Receipts** is described as the forty-fifth and ninety-fifth elements
**24. Independent Expenditures** is described as the fifty-third and hundred-and-third elements.

I'm willing to bet this riddle could be solved if there was an old paper form available to use as a sample. It seems likely that this is the result of a cut-and-paste exercise. The year is described as "19-", so I suspect no one has changed this in the last seventeen years.

The data includes  **Form F3XA**, **Form F3XN**, and **Form F3XT**, none of which is explicitly described. They are either the same, in which case no differentiation is required, or different, in which case, we need documentation.

**Comment by roberthadow** [comment]
Form 3 shares the same problem.   Data element 69 to the end have the same names as 24 to 68.  To be clear, they should be renamed to indicate Column A and Column B on the paper form

**Comment by jwchumley** [comment]
Not sure what the context here is.  The descriptions in the zip file are based on the form line numbers.  Row 45 is column A for line 19 and row 95 is column B for line 19.  
Rows 23 - 73 are column A and rows 74 to 123 are column B.

If you want to include "Column A" or "Column B" in each line that would be OK,  You could also use "This Period" and "Year-to-date" for form 3x (cycle to date for forms 3 and 3P)

Again, I don't know the context here.

**Comment by roberthadow** [comment]
Thank you, JW --

Now I understand.  When a data element is described twice, for example  Form F3X elements 23-73 and 74-123, assume the first batch is the left-most column, (column A for example) and so forth.

The context is that I read the data.  I need to determine that two items with the same description are in fact different, and what they are.
