### ISSUE TITLE
Publication date for FEC Record Articles?

### ISSUE THREAD

**Issue by amypike** [18F/FEC#3952]
Hi there!  This page shows the date "September 27, 2012" on the top right-hand corner of the page.  It may not be clear to users that this is the date the article was published in the FEC Record and it does not mean that this information was last updated September 27, 2012.   

https://beta.fec.gov/updates/voter-registration-activity-and-gotv/

Thanks!

**Comment by noahmanger** [comment]
Issue moved to [18F/fec-cms #973](https://github.com/18F/fec-cms/issues/973) via [**ZenHub**](https://www.zenhub.com/)
