### ISSUE TITLE
Search results for non-existent candidates

### ISSUE THREAD

**Issue by dvogel** [18F/FEC#3961]
I used the search auto-complete to navigate to:

https://beta.fec.gov/data/?search_type=candidates&search=THOMPSON%2C+JAMES+A+MR.

That page shows a single result, with the candidate's name linking to:

https://beta.fec.gov/data/candidate/H8KS04120/

But the next page is a "Not Found" error page.

Note: The candidate's campaign committee link does work:

https://beta.fec.gov/data/committee/C00631572/

**Comment by noahmanger** [comment]
Thanks for filing. This is a known bug with certain special election candidates. We have a fix coming in https://github.com/18F/openFEC-web-app/pull/1945

**Comment by noahmanger** [comment]
In the mean time, this link does work for that candidate: https://beta.fec.gov/data/candidate/H8KS04120/?election_full=false&cycle=2018

**Comment by noahmanger** [comment]
Hi @dvogel . Just following up to let you know that we shipped a fix for this. Thanks for filing!
