### ISSUE TITLE
Validation (ver 8.1)

### ISSUE THREAD

**Issue by roberthadow** [18F/FEC#3962]
The Filing guide is plain: "Fields may not begin with leading blanks."  The rule in FECCheck is similar:  "Leading Blanks {e.g. " TEXT"} not allowed." this is in the Error Section, not the Warning Section

This morning I discovered  95,000 occurrences of leading blanks since 1-Jan-17 in a single field in a single FORM_TYPE.

**Comment by jwchumley** [comment]
There are a number of things like this that we hope to improve in the upcoming eFiling system upgrade project. Thanks for pointing it out.

**Comment by noahmanger** [comment]
Thanks for reporting. No action to take now, so I'm closing.
