### ISSUE TITLE
Add punctuation to bulleted list https://beta.fec.gov/help-candidates-and-committees/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#3965]
Doing content QA. Added punctuation to the bulleted list in the PACs section. 

There are several types of nonconnected committees, including:
   
- Hybrid PACs,
- Leadership PACs and
- Super PACs (also called independent expenditure committees). 

URL: https://beta.fec.gov/help-candidates-and-committees/

<3 jme

**Comment by jenniferthibault** [comment]
Eeeeeeeee! @jamiealbrecht 👋 💖 ❣️

**Comment by emileighoutlaw** [comment]
Woohoo! Updated that page 😻
