### ISSUE TITLE
Add punctuation to bulleted list https://beta.fec.gov/help-candidates-and-committees/get-tax-id-and-bank-account/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#3968]
Doing content QA. I added punctuation and or to the following bulleted list per FEC content guide.

The account must be at one of the following:

-National bank,
-State bank or
-FDIC- or NCUA-insured institution.

url: https://beta.fec.gov/help-candidates-and-committees/get-tax-id-and-bank-account/

<3 jme

**Comment by emileighoutlaw** [comment]
TYVM!
