### ISSUE TITLE
Fix typo https://beta.fec.gov/help-candidates-and-committees/registering-candidate/house-and-senate-candidate-registration/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#3969]
Doing content QA. I think there's a typo in the last sentence of this paragraph:

The Statement of Candidacy requires a candidate’s signature. It collects some basic information, including the candidate's name and address. It’s also where candidates authorize any campaign committees working for them. A candidates for federal office are required to designate at least one authorized committee.

<3jme

**Comment by jamiealbrecht** [comment]
Also on this page, it doesn't seem consistent what we call the Statement of Candidacy. It's written the following ways on the page:

-Statement of Candidacy 
-Statement of Candidacy (Form 2)
-the Form 2
-Statement of Candidacy (FEC Form 2)

**Comment by emileighoutlaw** [comment]
Lovely work, Jamie! Fixed these issues!
