### ISSUE TITLE
Fix typo https://beta.fec.gov/help-candidates-and-committees/registering-candidate/other-agency-requirements/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#3970]
Doing content QA. In the following sentence, the "o" in "Of Government Ethics'" should be lower case. 

Presidential candidates should read the Office Of Government Ethics' legal advisory and contact the FEC's Office of General Counsel, General Law and Advice Division, 1-800-424-9530

Also on this page, because these are standalone sentences, I think there should be a period at the end of each bullet.

url: https://beta.fec.gov/help-candidates-and-committees/registering-candidate/other-agency-requirements/

<3 jme

**Comment by emileighoutlaw** [comment]
Grazi! Fixed!
