### ISSUE TITLE
Interactive Front End

### ISSUE THREAD

**Issue by Solomon** [18F/FEC#40]
I've built an interactive front end on top of FEC data, and I think it would be great if this functionality was something that the FEC itself provided!

Here's a link to the functionality of my front end: https://www.youtube.com/watch?v=_BUyIgGBNw8, and here's a link to a kickstarter campaign I'm currently running for it: http://kck.st/1DG57W4. The tool is already built (though not yet launched to the public), and if anyone at 18F or the FEC are interested in playing around with it, I will be happy to give access to a live version.

It's going to be completely open source, so I'd love to talk about how the FEC can take either some of the ideas, or just the actual project itself, and incorporate it into what you're doing.

**Comment by LindsayYoung** [comment]
Thanks for writing in, we would love to talk. Funny enough- we were just looking at you KickStarter page this morning. 

The repo for the website is - https://github.com/18F/openFEC-web-app 

We are building the site off of an API we are building with the data. The repo for that is https://github.com/18F/openFEC

**Comment by Solomon** [comment]
Ha, crazy timing. @LindsayYoung sent you an email to the email in your profile, let's chat sometime next week!
