### ISSUE TITLE
Replace semi-colons with commas in the bulleted list https://beta.fec.gov/help-candidates-and-committees/making-disbursements/fundraising-other-candidates-committees/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4012]
In the following bulleted list, we should use commas instead of semi-colons.

### Candidates running for both federal and nonfederal office

Commission regulations provide a limited exception for federal candidates and officeholders who seek state or local office. The restrictions on raising and spending funds outside the Act’s limitations and prohibitions do not apply to any federal candidate or officeholder who is or was also a candidate for state or local office so long as the raising or spending of funds is:

Solely in connection with his or her state or local campaign;

Refers only to him or her or to other candidates for that same state or local office; and

Is permitted under state law.

<3 jme

**Comment by jamiealbrecht** [comment]
On the same page, replace the semi-colon in the first line in this list. There should be no punctuation before the or. 

However, a federal candidate or officeholder (or agent of either) may not agree to the use of his or her name or likeness in publicity that contains a solicitation of funds outside the limitations and prohibitions of the Act or of Levin funds if the federal candidate or officeholder:

Is identified as serving in a manner specifically related to fundraising, such as honorary chairperson or member of a host committee; or 

Is identified in the publicity as extending the invitation to the event; or

Signs the communication.

**Comment by emileighoutlaw** [comment]
Lovely! Thank you!
