### ISSUE TITLE
Replace semi-colons in the bulleted list under candidate salary https://beta.fec.gov/help-candidates-and-committees/making-disbursements/personal-use/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4013]
In the following bulleted list, we should replace the semi-colons with commas.

### Candidate salary

The candidate may receive a salary from his or her campaign committee only under the following conditions:

The salary must be paid by the principal campaign committee;

The salary must not exceed the lesser of the minimum annual salary for the federal office sought or what the candidate received as earned income in the previous year;

Individuals who elect to receive a salary from their campaign committees must provide income tax records and additional proof of earnings from relevant years upon request from the Commission;

Payments of salary from the committee must be made on a pro-rata basis (i.e., a candidate may not receive a whole year’s salary if he or she is not a candidate for an entire twelve-month period);

Incumbent federal officeholders may not receive a salary payment from campaign funds; and

The first payment of salary shall be made no sooner than the filing deadline for access to the primary election ballot in the state in which the candidate is running for office.

<3 jme

**Comment by jamiealbrecht** [comment]
Also, on this page, we should delete the semi-colon in the following section: 

### Salary payments to candidate’s family

Campaign funds may be used to make salary payments to members of the candidate’s family only if:

The family member is providing a bona fide service to the campaign; and

The payments reflect the fair market value of those services.

**Comment by jamiealbrecht** [comment]
We should replace the semi-colons in this section too:

### Exceptions

No contribution will result, however, if the payment would have been made irrespective of the candidacy. For example, a third party may make the following payments on behalf of a candidate without making a contribution:

Payments to a legal expense trust fund established under House and Senate rules;

Payments for personal living expenses made from funds that are the candidate’s personal funds, including an account the candidate holds jointly with a family member; and

Payments that began prior to candidacy. For example, if the candidate’s parents had been making college tuition payments for the candidate’s children, the parents could continue to do so during the campaign without making a contribution.

**Comment by jamiealbrecht** [comment]
Replace the semi-colon here and delete the punctuation before and. 

### Salary or compensation paid to candidate

Compensation paid to a candidate by a third party as a continuation of payments made prior to candidacy (for example, payments of salary) are not considered contributions as long as such payments:

Result from bona fide employment independent of the candidacy;

Are exclusively in consideration of the services provided as part of this employment; and

Represent pay not in excess of that normally received for such services.

**Comment by emileighoutlaw** [comment]
Fixed these! Thanks!
