### ISSUE TITLE
Consistent use of commas in this bulleted list https://beta.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/personal-loans-candidate/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4014]
In the following bulleted list, there is one bullet that ends in a comma. I think they all should?

### Personal funds

The personal funds of a candidate include all of the following:

Assets which the candidate has a legal right of access to or control over, and which he or she has legal title to or an equitable interest in, at the time of candidacy

Income from employment

Dividends and interest from, and proceeds from sale or liquidation of, stocks and other investments,

Income from trusts, if established before the election cycle

Income from trusts established by bequests (even after candidacy)

Bequests to the candidate

Personal gifts that had been customarily received by the candidate prior to the beginning of the election cycle

Proceeds from lotteries and similar games of chance

<3 jme

**Comment by emileighoutlaw** [comment]
💟 ! Edited
