### ISSUE TITLE
Remove comma in the last list? https://beta.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/retiring-debts-candidate/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4015]
Should there be a comma before the or in this list?

#### Contributions exceeding net debts

If, on the same day, a campaign receives several contributions that, together, exceed the amount needed to retire its debts, the campaign may:

Accept a proportionate amount of each contribution and either refund the remaining amount or ask contributors to redesignate the excessive portions for another election, or

Accept some contributions in full and either return or refund the others or seek redesignations or reattributions for them.

**Comment by emileighoutlaw** [comment]
In this case I think yes, since it's more a compound sentence than a list of three things! 💟
