### ISSUE TITLE
Consistency for phone numbers https://beta.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/advances-individuals/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4016]
When we've written phone numbers on other parts of the site, we say for example, "call the Internal Revenue Service, 1-800-829-3676."

On this page under Congressional Staff, we say it this way: 

For more information about political activity by federal employees, contact the U.S. Office of Special Counsel at (202) 254-3600.

Do we want to make the way we write phone numbers consistent?

<3jme

**Comment by emileighoutlaw** [comment]
Great! xxx-xxx-xxxx is our preferred style! Making a note in the style guide now. :)
