### ISSUE TITLE
Fix punctuation in bulleted lists https://beta.fec.gov/help-candidates-and-committees/keeping-records/records-receipts/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4017]
In the following bulleted list, we should remove the semi-colon.

### Contributions of $50 or less

In advisory opinions, the Commission has recommended two possible accounting methods that satisfy recordkeeping requirements for contributions of $50 or less:

Keep the same information required for identifying contributions that exceed $50 (amount, date of receipt and contributor’s name and mailing address); or

In the case of small contributions collected at a fundraiser (such as gate receipts, cash contributions), keep records of the name of the event, the date and the total amount of contributions received on each day of the event.

<3jme

**Comment by jamiealbrecht** [comment]
Replace semi-colons with commas and delete the one before the and/or in the following sections:

### Contributions Exceeding $50

Records must identify each contribution of more than $50 by:

Amount;
Date of receipt; and
Contributor’s name and mailing address.

### Contributions Aggregating Over $200

For each contribution that exceeds $200, either by itself or when added to the contributor’s previous contributions made during the same calendar year, records must identify that contribution by:

Amount;
Date of receipt; and
Contributor’s full name and mailing address, occupation and employer.

### Distinguishing between primary and general contributions

If, before the primary election, a campaign receives contributions designated for the general election, it must use an acceptable accounting method to distinguish between primary contributions and general election contributions.

Acceptable accounting methods include:

Designating separate accounts for each election; or
Establishing separate books and records for each election.

### Contributions from political committees

Records must identify each contribution from a political committee, regardless of amount, by:

Amount;
Date of receipt; and
Name and address of the political committee.

### Possibly illegal contributions

Contributions: When a committee has reason to question the legality of a contribution, it has specific time frames in which to clarify whether the contribution is permissible. While investigating a contribution, the committee must keep a written record noting the basis of concern for each deposited contribution which:

Requires a written redesignation and/or reattribution from the contributor; or
Requires confirmation that it is not from a prohibited source.

The request for the information and the best efforts notification must be clear and conspicuous. If the solicitations include response materials, the best efforts notice and the request for the contributor information must be placed on these materials. The notice will not be considered to be “clear and conspicuous” if:

The notification is printed in smaller type than the solicitation and response materials;
The printing is difficult to read; or
The notification is placed where it can be easily overlooked.

### File amendments if necessary

If requested information about a contribution is received after the contribution has been disclosed on a report, the committee must either:

File a Schedule A with its next regularly scheduled report, containing memo entries listing all contributions for which new contributor information has been received; or
File amendments to the original reports.

**Comment by emileighoutlaw** [comment]
**J**eepers! Look at
**A**ll these
**M**agnificent edits.
**I** made them. Thank you!
-**E**mileigh

**Comment by jamiealbrecht** [comment]
**E**eeek! I can't
**M**essage you to say
**I** will miss you
**L**onger than
**E**ver
**I**'ll remember
**G**overn in poetry 
**H**ere together

**Comment by jamiealbrecht** [comment]
I tried <3333

**Comment by emileighoutlaw** [comment]
Love this so much <333333

**Comment by jenniferthibault** [comment]
I see you two being wonderful over here 😻
