### ISSUE TITLE
Fix punctuation in bulleted lists https://beta.fec.gov/help-candidates-and-committees/keeping-records/records-disbursements/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4018]
In the following sections, replace the semi-colons with commas and delete the punctuation before the and/or.

The committee must keep a record of each disbursement, including:

Amount;
Date;
Name and address of payee; and
Purpose (a brief but specific description of why the disbursement was made, such as “dinner expense” or “postage”).

### Advances for travel and subsistence

When a committee advances $500 or less to the candidate, staff members or volunteers for travel expenses—including transportation, food and lodging—the committee must retain:

The expense voucher or other expense account documentation; and
The canceled check made out to the individual receiving the payment.

When a committee advances more than $500 for travel and subsistence expenses, the committee must obtain and retain:

A receipt (or invoice) from the person providing goods or services in excess of $200 per transaction to the person requesting the advance;
A cancelled check from the person requesting the advance showing payment to the person providing goods or service; or
A monthly credit card billing statement or customer receipt from the person requesting the advance, and that person’s cancelled check showing payment of such bill.

### Credit card transactions

For credit card transactions, the committee must retain:

A monthly billing statement; or
The customer receipt for each transaction; and 
The canceled check used to pay the credit card account.

<3jme

**Comment by emileighoutlaw** [comment]
Woohoo! Thanks for spotting those hideous semi-colons!
