### ISSUE TITLE
Phone number format inconsistency https://beta.fec.gov/help-candidates-and-committees/keeping-records/misappropriated-funds/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4019]
Here is another section where we write a phone number two different ways.

If a committee discovers a misappropriation or embezzlement of committee funds, the Campaign Finance Analyst assigned to the committee can help work through the resulting disclosure challenges. Call toll-free at 1-800-424-9530, press #5, or 202-694-1130. Committees may also want to consult with legal counsel to see whether filing a sua sponte submission or complaint may be appropriate. Committees who would like to discuss a sua sponte submission with the FEC  may contact the Office of General Counsel (202-694-1650).

**Comment by emileighoutlaw** [comment]
Oh good catch! Thank you. Fixed.
