### ISSUE TITLE
Remove semi-colon in bulleted list https://beta.fec.gov/help-candidates-and-committees/keeping-records/misappropriated-funds/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4020]
In the following list, we should remove the semi-colon:

There are two ways to do so:

Adjust the beginning COH balance of the report manually, with memo text referencing the earlier Miscellaneous Documents (Form 99); or

Make a one-time COH adjustment entry on Schedule B (Line 21/Form 3; Line 29/Form 3X) with the purpose: “Cash-on-hand adjustment due to unauthorized disbursements.”

<3 jme

**Comment by emileighoutlaw** [comment]
Woot! Fixed 😍 . Thanks @jamiealbrecht!!
