### ISSUE TITLE
Add commas to bulleted list https://beta.fec.gov/help-candidates-and-committees/filing-reports/48-hour-notices/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4024]
In the following bulleted list, I think there should be commas: 

This reporting requirement applies to all types of contributions to authorized candidate committees, including:

Contributions from the candidate
Joint fundraisers in which the campaign participates
Loans from the candidate and other non-bank sources
Endorsements or guarantees of loans from banks

<3jme

**Comment by emileighoutlaw** [comment]
Rad! I updated the microcopy so we didn't have to punctuate this list 😁
