### ISSUE TITLE
Phone and fax number format consistency https://beta.fec.gov/help-candidates-and-committees/filing-reports/48-hour-notices/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4025]
How do we want to write phone and fax numbers?

In the following section, it's written two different ways:

Submission requirements

House candidate committees file either online or by paper with the FEC.  

Electronic filers must use the Form 6 and file electronically.  
Paper filers can file the Form 6 by fax (202-219-0174). 

Senate candidate committees always file by paper with the Secretary of the Senate. The Secretary of the Senate provides the option of filing by fax at 202-224-1851.

**Comment by emileighoutlaw** [comment]
danke schön! Should be 202-224-0174. Fixed!
