### ISSUE TITLE
Table is hard to read https://beta.fec.gov/help-candidates-and-committees/filing-reports/post-general-election-reports/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4026]
Hi! I know this isn't exactly what I was asked to look at, but the table on this page is a bit hard to read. Maybe just a bit more space in between the columns dates covered and due?

<3 <3 <3

**Comment by emileighoutlaw** [comment]
Ohhh, good find! Pinging @jenniferthibault to take a look. The table spacing does seem a little tight:

![screen shot 2017-05-02 at 10 04 31 am](https://cloud.githubusercontent.com/assets/10552702/25624264/7a22cee0-2f1e-11e7-9a3d-41e95a15ab14.png)

**Comment by jenniferthibault** [comment]
Resolved by https://github.com/18F/fec-style/pull/737
