### ISSUE TITLE
Add colon after sentence https://beta.fec.gov/help-candidates-and-committees/winding-down-candidate-campaign/winding-down-costs/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4034]
In the following section, should there be a colon after include?

Campaign funds may be used to pay ordinary and necessary expenses incurred in connection with one’s duties as a federal officeholder. Such expenses include the costs of winding down the office of a former federal officeholder for a period of six months after he or she leaves office. Winding down costs include the following.

Moving expenses: A retiring federal officeholder may use campaign funds to pay for the expenses of moving office and personal furnishings from the congressional office in Washington, DC, back to the officeholder’s home state. While the costs of transporting an officeholder’s personal household effects and furnishings from Washington, DC, to the officeholder’s home state are not “winding down costs,” such costs are “ordinary and necessary expenses” incurred in connection with ending his or her duties as a federal officeholder. All such moving expenses should be reported as “other disbursements” by the officeholder’s committee, with specific payee(s) and purpose noted.

Payments to committee staff. See AOs 1976-90 and 1978-43.

Gifts: Campaign funds may be used to purchase gifts or make donations of nominal value to persons other than the members of the candidate’s family.

<3 jme

**Comment by emileighoutlaw** [comment]
Beautiful! <3 <3 <3 and thanks!
