### ISSUE TITLE
Capitalization question for https://beta.fec.gov/about/plain-language/plain-writing-compliance-report-april-13-2016/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4040]
In the following sentence, is Senior Official Responsible a title or is there a reason its capitalized? It's a bit hard to read. 

Greg Scott, Assistant Staff Director, Information Division, Office of Communications, is the Federal Election Commission’s Senior Official Responsible for Plain Writing.

<3 jme

**Comment by emileighoutlaw** [comment]
I think it is a title, although I agree it's tough to read :(
