### ISSUE TITLE
Formatting questions and thoughts for https://beta.fec.gov/about/no-fear-act/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4041]
Hello! A few things I noticed on this page:

1. The first time we mention the EEO Office in the third paragraph we use the acronym. Should we write it out?
2. I think anti-discrimination has a hyphen. 
3. Under anti-discrimination laws, one of the paragraphs is in a different font and size.
4. In the following paragraph and throughout this page, we're using and/or, which I've found a bit difficult to read.

> If you are alleging discrimination based marital status or political affiliation, you may file a written complaint with the U.S. Office of Special Counsel and/or the Merit Systems Protections Board (MSPB), as applicable. 

5. Under Whistleblower protection laws, I wonder if the first paragraph would be easier to parse if it were in a bulleted list similar to other parts of the site?

<3 jme

**Comment by emileighoutlaw** [comment]
Pinging @AmyKort — I think these are really easy fixes and good ideas. @llienfec could easily make these changes in Wagtail in 2 minutes if you give them the 👍

**Comment by llienfec** [comment]
Hi all, updated items 1-4 above.  For the and/or problem, I changed those instances to something like "USOSC, MSPB, or both as applicable" so that meaning isn't changed.  

For #5 - Really good comment that this is a tough paragraph to parse. @jamiealbrecht  - do you have suggestions for what part we should bullet out?  I think there are 3 different sections that are contenders, but not sure how to make the paragraph clearer.  Thanks for your detailed review!

**Comment by llienfec** [comment]
Also: Leaving "antidiscrimination" the name of the No FEAR Act b/c it's the official name. Changed to hyphenated in the rest of the text.

> Notification and Federal Employee Antidiscrimination and Retaliation Act of 2002 (No FEAR Act).

**Comment by jamiealbrecht** [comment]
@llienfec thanks for the comments! What about something like this: 

A federal employee with authority over personal actions must not use the authority to take, fail to take or threaten to take or fail to take a personnel action against an employee or applicant because of disclosure of information by that individual that is reasonably believed to evidence:

	•	violations of law, rule or regulation,
	•	gross mismanagement,
	•	gross waste of funds,
	•	an abuse of authority, or
	•	a substantial and specific danger to public health or safety, 

unless disclosure of such information is specifically required by Executive Order to be kept secret, in the interest of national defense or the conduct of foreign affairs.

What do you think?

**Comment by llienfec** [comment]
Awesome.  Thanks @jamiealbrecht   Added the bullets and it's live on beta now.  Appreciate the help.  Can you close the issue?  I don't have access to close it out.

**Comment by jamiealbrecht** [comment]
Will do! Thank you. :)
