### ISSUE TITLE
Add parenthesis https://beta.fec.gov/legal-resources/enforcement/audit-reports/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4046]
On this page, under Title 26 audit reports, there is a missing parenthesis. 

Title 26 audit reports

Federal law requires the Commission to audit every political committee established by a candidate who received public funds and every Presidential nominating convention committee that received public funds. The audit determines whether the committee used the public funds in accordance with the law, and whether the committee otherwise complied with the limitations, prohibitions, and disclosure requirements of the election law. The law also requires the Commission to audit host committees (local organizations whose principle objective is the encouragement of commerce in the city where a national nominating convention is held.

<3 jme

**Comment by emileighoutlaw** [comment]
Fixed! 💘 It has been such a pleasure working with you, jme
