### ISSUE TITLE
Candidate Summary individuals should match up with bulk data individuals

### ISSUE THREAD

**Issue by Solomon** [18F/FEC#41]
When you look at a Candidate Summary from fec.gov, and compare the list of individual contributions from clicking on the link to the individual contributions from the data dump, they are not the same.

In particular, it seems like a bunch of law firms and LLC's are included in the candidate summary view, but are not included in the bulk data. I would rather include them in the individual contribution bulk data, because then it becomes possible to correctly calculate unitemized contributions to a candidate, but either way, I think they should match.

Second question, are those LLC and LLP contributions located anywhere in the bulk data?

**Comment by dwillis** [comment]
If by bulk data you mean the FTP files, that's because LLCs and LLPs' contributions are reattributed to their partners/members as individuals, as the law requires. That practice, in my experience, does not affect the unitemized contributions total, which in any case is provided in the summary.
