### ISSUE TITLE
Loading animation not displaying on data tables

### ISSUE THREAD

**Issue by jenniferthibault** [18F/FEC#4109]
All that's showing up is the solid background, but not the loading animation:

<img width="1272" alt="screen shot 2017-05-25 at 9 24 13 am" src="https://cloud.githubusercontent.com/assets/11636908/26452035/6f8b96a4-412c-11e7-809b-ab064365e02f.png">

cc @noahmanger

**Comment by noahmanger** [comment]
Will be resolved by https://github.com/18F/openFEC-web-app/pull/2083
