### ISSUE TITLE
Individual Contributions not appearing

### ISSUE THREAD

**Issue by jbucelato** [18F/FEC#4138]
We have received several phone calls in Public Records about individual contributions not appearing for Carson America for 2016.
https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2016&committee_id=C00573519&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016
Had to show them on the Classic site.

Jason (Public Records)

**Comment by noahmanger** [comment]
Thanks @jbucelato . Looking into it (and moving this issue to the OpenFEC API repo).

**Comment by noahmanger** [comment]
Issue moved to [18F/openFEC #2442](https://github.com/18F/openFEC/issues/2442) via [**ZenHub**](https://www.zenhub.com/)
