### ISSUE TITLE
Filtering search results by state

### ISSUE THREAD

**Issue by patphongs** [18F/FEC#4185]
I cover politics for The Santa Fe New Mexican and use the FEC website daily to search for, among other things, statements of organization filed by committees in my state. While I appreciate the new design, please consider adding a feature that allows users to filter search results by state. 

Webmanager user feedback

**Comment by noahmanger** [comment]
Thanks! We already have an issue for this here https://github.com/18F/openFEC/issues/2378 . Probably worth bumping this up to next sprint as this is the third time we've gotten this request.
