### ISSUE TITLE
Committee ID question

### ISSUE THREAD

**Issue by patphongs** [18F/FEC#4186]
The new FEC website is only showing an old committee for US House Rep. Valdez Demings from FL-10.  Committee ID# C00498980 is the only searchable committee for her and it is old.  Committee ID #C00590489 is her current and active committee.   

Webmanager's Inbox

**Comment by noahmanger** [comment]
@jwchumley can you look into this?

**Comment by noahmanger** [comment]
This page is there and is showing up in the autocomplete:
![image](https://user-images.githubusercontent.com/1696495/27348913-783be9d8-55aa-11e7-92bd-8bb37aeb347d.png)
