### ISSUE TITLE
Candidate Summary from pre-2008 for small money donations

### ISSUE THREAD

**Issue by Solomon** [18F/FEC#42]
Would it be possible to allow the download, or put on the ftp site, candidate summary data from pre-2008, in the format you have for 2008 and onwards?

If not, could I get some guidance around how to figure out unitemized donations from before 2008?

I tried using the space-delimited files for can_sum on the ftp site, but there doesn't seem to be a way to pull the small money donation amount from that file format.

I've also tried subtracting all the individual donations from the total individual donations from the candidate summary, but the numbers don't match up for the following reasons: 1) the bulk data individual contributions don't include contributions from LLC's and LLP's, which can significantly affect the total donations, and 2) small donations from donors who already gave previous reported donations are not included. So, if I gave $2,000, and then the next day I gave $50, that $50 is not included in the bulk download.

**Comment by LindsayYoung** [comment]
In the [candidate summary file](http://www.fec.gov/finance/disclosure/ftpsum.shtml) there is a row labeled `ind_uni_con`, that will be the total donations under $200 for that reporting period. I think that is what you are looking for, correct?

**Comment by Solomon** [comment]
That column doesn't seem to be included in the files available for download: http://www.fec.gov/finance/disclosure/metadata/DataDictionaryWEBALL.shtml
