### ISSUE TITLE
Highlight Live Commission Meetings

### ISSUE THREAD

**Issue by patphongs** [18F/FEC#4200]
There is a request to highlight the live commission meeting more. On the legacy site, the live broadcast was one click from the landing page. Now visitors need to click to the agenda meeting to know that there is a live broadcast. How can we better inform visitors about the live broadcast?

This has now been requested by 2 users.

**Comment by noahmanger** [comment]
Would using the generic homepage update type solve this? That basically lets you post any link to the home page with any text.

**Comment by patphongs** [comment]
Figuring out What's Happening and Upcoming events we might want to figure out how to overall put out notifications (efiling, maintenace, live video streaming)

I think being able to tack on a trigger to the Live video and Live captioning , so turning that onto the 

Tacking on a
