### ISSUE TITLE
Missing end dates for some ranges

### ISSUE THREAD

**Issue by rshorey** [18F/FEC#4201]
When I look at [money raised for the current period](https://www.fec.gov/data/committee/C00633362/?tab=summary), the date range appears as "01/01/2017-None". It's pretty minor, but would help a lot to know when the information is valid through.

screenshot:
![screen shot 2017-06-08 at 9 37 21 am](https://user-images.githubusercontent.com/901091/26931668-4a27f6ec-4c2f-11e7-967f-3184126a569e.png)

Thanks!

**Comment by jontours** [comment]
Hey @rshorey these inconsistencies will be remedied by the work here: https://github.com/18F/openFEC/pull/2454.  Which should be making it's way into production soon.  Thanks for flagging the issue.

-Jon Carmack

**Comment by rshorey** [comment]
great, appreciate it, thanks!

**Comment by noahmanger** [comment]
This fix was just shipped today. Closing!
