### ISSUE TITLE
Latest Update link issue

### ISSUE THREAD

**Issue by jjones0618** [18F/FEC#4289]
The link https://www.fec.gov/updates/?update_type=meetings leads only to the generic Latest Updates page instead of to the Commission meetings option on that page. Can this link be made functional or should it already be so?

**Comment by jjones0618** [comment]
Issue resolved by removing errant period at end of link!

**Comment by jjones0618** [comment]
#

**Comment by jenniferthibault** [comment]
@jjones0618 it's always great when issues resolve themselves! Thanks for all the constructive feedback, I've been thinking about a few other things you've written in about and will follow up on those threads.
