### ISSUE TITLE
presidential downloads

### ISSUE THREAD

**Issue by PaulClark2** [18F/FEC#429]
From betafeedback@fec.gov: 

Hello, 

I really like the beta version of your website, but seems I am unable to download Presidential candidate campaign finance data by contributors state, employer, occupation, etc.  I know there are other parts of the website where data exporting is possible so would be nice to do it here too.  If I am mistaken, please let me know. 

Thanks 
Ian

**Comment by noahmanger** [comment]
We shipped the ability to download these tables a while ago. Closing.
