### ISSUE TITLE
Historical filings

### ISSUE THREAD

**Issue by mehulkar** [18F/FEC#43]
programmatically access historical filings of candidates and cross reference them with a list of presidents

**Comment by LindsayYoung** [comment]
Thanks for posting!

What kind of date range are you thinking of? 

These are the current offerings of bulk downloads that start in 1980, if that is helpful-
http://www.fec.gov/finance/disclosure/ftpdet.shtml

**Comment by mehulkar** [comment]
All of those are great :)

Basically turning those `cn*.zip` files from FTP access to HTTP and from CSV to JSON would be great.

**Comment by mehulkar** [comment]
heck, now that I know exactly where those are, I could convert and expose a basic version of that endpoint.

**Comment by LindsayYoung** [comment]
Glad we could help!
