### ISSUE TITLE
Fix bug in H4 html viewing

### ISSUE THREAD

**Issue by selenehs** [18F/FEC#44]
When looking through committee reports that contain joint allocated federal/nonfederal activity in HTML format, any attempts to open Schedule H4 result in the following:

ORACLE error-- ORA-00904: "DESCRIPTION": invalid identifier :

Example: http://docquery.fec.gov/cgi-bin/forms/C00010439/1010437/h4

Currently the only way to read Schedule H4s is in PDF format, which makes research quite a bit slower.

Is this something that can be fixed?

**Comment by PaulClark2** [comment]
This has been fixed

**Comment by selenehs** [comment]
Thanks!

--
Selene Hofer-Shall
802-578-7250

*NOTICE:  This e-mail contains information intended only for the addressee
named. D**isclosure or use of the contents of this e-mail without the
express consent of the sender is prohibited.* *If you have received this
e-mail in error, please notify the sender immediately via return email.
Thank you.*
