### ISSUE TITLE
Information exported in CSV

### ISSUE THREAD

**Issue by busterroni** [18F/FEC#443]
First of all, fantastic job with the new site, it's a major improvement from the original and a pleasure to navigate.

When you export, for example, the data on [this](https://beta.fec.gov/data/disbursements/?two_year_transaction_period=2016&recipient_name=domino%27s&recipient_name=little+caesers&recipient_name=papa+gino%27s&recipient_name=papa+john%27s&recipient_name=pizza&recipient_name=pizzeria&recipient_name=sbarro) page, mostly everything is exported. One thing that isn't exported that I would like to have is the `spender` name. The spender `committee_id` is exported, and from that you can obtain the name, but I think it would be easier to just export the `spender` name.

Please let me know if I'm missing something or if any clarification is needed. Thanks again for the great site.

**Comment by busterroni** [comment]
Actually, this appears to be a duplicate of #435-- sorry for not searching first!

**Comment by jenniferthibault** [comment]
Thanks so much for filing this @busterroni — even if it was a duplicate issue, it's never bad to have more than one person reinforce it!

After feedback comes into this repository, we often move issues to the working repo most relevant to the specific issue. We have quite a few repositories for this site, so this sorting helps keep our workflow organized. The original issue from #435 has been moved to https://github.com/18F/openFEC/issues/1894 , where we'll work on it until it's resolved. Feel free to follow along for updates.

Thanks again!
