### ISSUE TITLE
Pagination doesn't seem to be working on spending page

### ISSUE THREAD

**Issue by rshorey** [18F/FEC#4433]
On [this page](https://www.fec.gov/data/committee/C00503789/?tab=spending#total-disbursements), when I hit the next page button, it advances the count but doesn't change data. I know there is more data because when I ask for 100 entries per page it shows me more rows.

Before clicking the right "next" arrow:
![screen shot 2017-08-02 at 11 52 18 am](https://user-images.githubusercontent.com/901091/28882505-6e13d7e0-7779-11e7-986d-5afbe629eefd.png)

After clicking the right "next" arrow (note that the count is different but the data is the same):
![screen shot 2017-08-02 at 11 52 26 am](https://user-images.githubusercontent.com/901091/28882527-7d12efc4-7779-11e7-95dd-25aab1d22898.png)

**Comment by jenniferthibault** [comment]
Thanks so much for reporting @rshorey. We have a fix in progress in https://github.com/18F/openFEC-web-app/pull/2224 for a similar issue reported, but I'd like @noahmanger to confirm it's the same problem & same fix.

**Comment by noahmanger** [comment]
Yep! Same issue, just waiting to deploy the code.

**Comment by rshorey** [comment]
thanks friends!

**Comment by noahmanger** [comment]
Closing since the work is done and pending deployment.
