### ISSUE TITLE
Calendar Entry Detail Alignment

### ISSUE THREAD

**Issue by jjones0618** [18F/FEC#4557]
The calendar detail box that opens when I click any entry from the month-at-a-glance view is partially blocked by the side menu. It appears to be anchored in place as the box doesn't adjust as I re-size my browser window.

Chrome Version 60.0.3112.113 (Official Build) (64-bit) on a Mac

![screen shot 2017-09-26 at 9 36 15 am](https://user-images.githubusercontent.com/10223901/30863145-4217e6f4-a29e-11e7-9af8-ad95ee7ef9c9.png)

**Comment by JonellaCulmer** [comment]
This issue was also logged yesterday in FEC-cms #1271

**Comment by JonellaCulmer** [comment]
Issue moved to [18F/fec-cms #1274](https://github.com/18F/fec-cms/issues/1274) via [**ZenHub**](https://www.zenhub.com/)
