### ISSUE TITLE
Party error https://www.fec.gov/data/candidate/S8AZ00197/

### ISSUE THREAD

**Issue by shmcminn** [18F/FEC#4588]
Not sure if this is the place to report it, but Dem. Rep. Krysten Sinema is listed as a Republican ... 

https://www.fec.gov/data/candidate/S8AZ00197/

**Comment by PaulClark2** [comment]
Thank you for contacting the FEC. I've corrected Ms. Sinema's party affiliation. You should see the update on the website tomorrow morning.
