### ISSUE TITLE
Data missing?

### ISSUE THREAD

**Issue by busterroni** [18F/FEC#469]
Sorry if this isn't the correct place to ask, as it might be more related to FEC records than the website's backend.

I think the website is missing some data, specifically for 2016 Presidential candidate Lawrence Lessig (P60009685). [He has a page](http://www.fec.gov/fecviewer/CandidateCommitteeDetail.do?candidateCommitteeId=P60009685&tabIndex=1) on the original FEC website, but not on the beta version ([this URL](https://beta.fec.gov/data/candidate/P60009685/) is where it would exist).

Something interesting I noticed is that the original FEC website says it has no reports on file of the donations his campaign received, despite it having raised over $1,000,000. If I had to guess I would say this is related to the beta website not having him on record, but I'm not sure.

I apologize again if this is the wrong place to ask. If it is, please let me know and I'll direct the question to the right group.

**Comment by busterroni** [comment]
Bumping this-- would appreciate knowing why the data is unavailable.

**Comment by LindsayYoung** [comment]
Thanks for writing in! It seems like the issue is that we have an incorrect date. We will see where that is coming from and fix it.
<img width="696" alt="screen shot 2016-09-26 at 9 26 43 am" src="https://cloud.githubusercontent.com/assets/4406333/18842876/61df20b2-83cb-11e6-9cf8-0842540bddfb.png">

**Comment by LindsayYoung** [comment]
scratch that- the data is someone else

**Comment by busterroni** [comment]
Bump, still wondering why the data is missing.

**Comment by LindsayYoung** [comment]
Thanks for the ping on this! It looks like he doesn't currently have an authorized or principal committee, so he is falling out of one of our joins. @jontours figured this out and is working on how to make that join more forgiving to ensure all candidates show up.

**Comment by noahmanger** [comment]
This now works.
