### ISSUE TITLE
FEC-CMS repo Readme.md update needed

### ISSUE THREAD

**Issue by cptechiegal** [18F/FEC#4755]
The following items need updating at the FEC-CMS Readme.md
1)Update the section on: Create local databases and/or Restoring your local database from a backup
a) To include info on setup of local database from a backup 
(as is done at openFEC repo section:Load our sample data into the development database)
 additional information on the sample DB dump setup for <path/to/backup_file>
b) And maybe add the sample DB dump into the repo files
(as is done in the OpenFEC repo for the DB dump file)
c) To include warning added about: ./manage.py update_all
i.e., never to 'update all' when pointing to an rds box via the SQLA_CONN env var
2) Update the section on:Developing with openFEC  and / or Set local environment variables
To include information on the setup for using the cloud API instead of local config with env var:
export FEC_API_URL=https://fec-dev-api.app.cloud.gov/

**Comment by cptechiegal** [comment]
Will make a PR for this instead.

**Comment by jenniferthibault** [comment]
For the same reasons mentioned in https://github.com/18F/FEC/issues/4753, it's better to leave this open and assign it to you, @cptechiegal if you're taking the work on. 

I'll re-open this, assign it to you, and when your PR that addresses it is merged in, we can close it again 🎉 .

**Comment by cptechiegal** [comment]
completed updates

**Comment by cptechiegal** [comment]
This has been completed as of 12/05/17 as PR#1619 https://github.com/18F/fec-cms/pull/1619
