### ISSUE TITLE
Filters not filtering for IEs

### ISSUE THREAD

**Issue by rshorey** [18F/FEC#4782]
I added a bunch of filters to the independent expenditure search, but it appears to be showing me everything. I tried on multiple browsers (including one that won't have any cached visits to FEC sites)

Here's the URL:
https://www.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C30001911&committee_id=C90013244&cycle=2014&is_notice=false

here's a screenshot of it showing my filters and then showing a bunch of unrelated results:
![screen shot 2017-11-30 at 12 13 10 pm](https://user-images.githubusercontent.com/901091/33444463-61e9d3a4-d5c8-11e7-8db8-0f8bc4a97d57.png)

Thanks!

**Comment by LindsayYoung** [comment]
thanks for reporting @rshorey!

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1614](https://github.com/18F/fec-cms/issues/1614) via [**ZenHub**](https://www.zenhub.com/)
