### ISSUE TITLE
Roy Moore and Doug Jones filing links are dead

### ISSUE THREAD

**Issue by rshorey** [18F/FEC#4790]
The links to the PDFs of Moore and Jones' pre-special alerts are dead. The election is only 7 days away, so would appreciate a quick fix if possible.

When I click on the PDF link on this page:

https://www.fec.gov/data/committee/C00639401/?cycle=2018&tab=filings

I get this link, which is a 404:
http://docquery.fec.gov/pdf/207/201712010200403207/201712010200403207.pdf

Thanks!

**Comment by AmyKort** [comment]
Thanks for reaching out! Those links should be working now.
