### ISSUE TITLE
API keys claim to give you 120 calls per minute but they don't

### ISSUE THREAD

**Issue by rshorey** [18F/FEC#4816]
I just got a new api key (I lost my previous one, sorry) which promises 120 calls per minute.

But it's not resetting after a minute. (I waited 65 seconds, and it's still not finding the key "results").

![screen shot 2017-12-15 at 4 38 27 pm](https://user-images.githubusercontent.com/901091/34061469-8276678c-e1b6-11e7-94aa-14c61cb9071a.png)

Could you please either change the permissions for the keys or change the documentation so I know what to expect?

Thanks!

**Comment by LindsayYoung** [comment]
Thanks for writing in @rshorey! We will fix the documentation. 

We have been manually adjusting people who have emailed us so I have adjusted your key to be 120 a minute.

Here is the issue for our follow up steps:
https://github.com/18F/openFEC/issues/2819
