### ISSUE TITLE
make it easier to tell which cycle I'm searching in

### ISSUE THREAD

**Issue by rshorey** [18F/FEC#482]
It is not very clear that a contributions search is in the current cycle only unless I manually change it, and the button to manually change is hidden in the transaction tab.

Specifically, if I [go to the contributions search page and search for Romney for President](https://beta.fec.gov/data/receipts/?two_year_transaction_period=2016&committee_id=C00431171&min_date=01%2F01%2F2015&max_date=09%2F28%2F2016&is_individual=true), I get no contributions and panic for a moment before remembering that I need to open the transactions tab and select the current cycle.

![screen shot 2016-09-28 at 2 03 17 pm](https://cloud.githubusercontent.com/assets/901091/18926125/9ac62730-8584-11e6-95c4-193f823f8aa0.png)

I recommend fixing this by either:
1. Requiring the user to select the desired cycle every time or
2. Making it blindingly obvious at the top which cycle is being searched (and if no contributions come up, maybe helpfully suggesting that the user might want to confirm the cycle?) The parameter on the top is not super obvious unless you know to look for it.

Thanks!

**Comment by noahmanger** [comment]
Thanks for writing in @rshorey ! This totally makes sense. We've heard elsewhere from people requesting these filters be arranged in similar ways. We'll look into it and might have follow up questions.

**Comment by noahmanger** [comment]
Long time coming, but this a change to this effect is now being implemented in https://github.com/18F/openFEC-web-app/pull/2083 (in addition to working on expanding the amount of time that can be searched at once).

**Comment by noahmanger** [comment]
Doing some housekeeping. We have a fix coming very soon to expand/remove the time period constraint on this search, and in the mean time, we raised the prominence of the cycle filter, so I'm going to close. Thanks!

**Comment by rshorey** [comment]
Thanks, appreciate it!
