### ISSUE TITLE
Migrating Google Analytics to FEC

### ISSUE THREAD

**Issue by karareinsel** [18F/FEC#4896]
Wanted to get this task documented so that it can be accounted for in the migration. Ultimately it might break down into smaller tasks. At the moment, this task is more research focused so that we know exactly the current state and then can plan and execute the transition plan.

[ ] Kara to speak with Tim Lowden from DAP team
[ ] Audit all existing FEC Google Analytics (GA) accounts - ownership, usage, properties 
[ ] Enable Google Search Console for FEC
[ ] Create Campaign Tracking URL generator spreadsheet
[ ] Provide recommendations for long-term GA account structure - property level, views, etc.

**Comment by PaulClark2** [comment]
Closed in favor of https://github.com/18F/fec-transition/issues/167
