### ISSUE TITLE
"Reattribution & Refunds" in Contributor Data files

### ISSUE THREAD

**Issue by gouldc2** [18F/FEC#49]
For each candidates contributor files there are entries for amounts over $2700 that are flagged with Reattribution, or other entries of a negative amount that says Refund. Looking at these it is hard to tell how many people donated, or how much because these need to be manually taken out of the file. Could the FEC publish their post-analysis file which they took these into account to get money donated by amount i.e. <$200, $200-$500, etc? Also include the number of donors, and if a donor is a repeat.

**Comment by LindsayYoung** [comment]
Donor data is self reported by the filers and can get a messy at times. There are no donor ids and names are not very good identifiers, for example, the same person can appear as Jim M. Jones, James Jones etc. 

You can find the data that is reported on this on the beta website at https://beta.fec.gov/data/receipts/ and the  [/schedules/schedule_a](https://api.open.fec.gov/developers/#!/schedules%2Fschedule_a/get_schedules_schedule_a) endpoint on the API. 

We are working on custom downloadable datasets and there is the traditional FEC [bulk data](http://www.fec.gov/finance/disclosure/ftpdet.shtml).

Thanks for writing in!
