### ISSUE TITLE
Duplicate search terms are entered when searching for individual contributors, results seem unaffected

### ISSUE THREAD

**Issue by ethanheppner** [18F/FEC#490]
<img width="966" alt="screen shot 2016-10-06 at 1 28 06 pm" src="https://cloud.githubusercontent.com/assets/12718798/19166483/4e3b95f4-8bcd-11e6-9d7b-2a6440f10a27.png">

**Comment by xtine** [comment]
This seems to happen when pressing enter on text inputs on Safari.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/536
