### ISSUE TITLE
Presidential campaigns before 2008 don't have contribution data  

### ISSUE THREAD

**Issue by 1wheel** [18F/FEC#510]
https://beta.fec.gov/data/committee/C00383653/?cycle=2004&tab=receipts

I'm not sure the FEC was collecting this info before 2008 - the old 17 (a) line item doesn't have a place for unitemized data: 
![image](https://cloud.githubusercontent.com/assets/1643998/19662355/18b0f078-9a05-11e6-9590-cbc6fbdc5250.png)
http://docquery.fec.gov/pdf/001/24961730001/24961730001.pdf

While the current one does:
![image](https://cloud.githubusercontent.com/assets/1643998/19662407/43112df6-9a05-11e6-96c1-be27dde1b3f8.png)
http://docquery.fec.gov/cgi-bin/forms/C00575795/1066337/

I think the breakdown of unitemized v itemized is derivable from the top line number of individual contributions and summing the [itemized contributions](http://www.fec.gov/finance/disclosure/ftp_download.shtml). Not sure that's in scope of this project to do that, but a note on the webpage and N/As in the [exported data](https://beta.fec.gov/data/reports/presidential/?data_type=processed&committee_id=C00383653&is_amended=false) might be helpful.

**Comment by noahmanger** [comment]
Thanks for filing and apologies for the delay in responding to this. You raise a great point. Yeah, I don't think we want to derive totals but agree that a note and N/As could be helpful. I'm going to copy this over to our main repos to get it in our regular work flow.

**Comment by noahmanger** [comment]
Issue moved to [18F/openFEC-web-app #1681](https://github.com/18F/openFEC-web-app/issues/1681) via [**ZenHub**](https://www.zenhub.com/)
