### ISSUE TITLE
Language change on RFAI page

### ISSUE THREAD

**Issue by llienfec** [18F/FEC#559]
RAD management requests to change language on https://beta.fec.gov/registration-and-reporting/request-additional-information/ (highlight attached) to:

Resource constraints limit our ability to reach out when we receive your additional responses and amendments.  If you have further questions, please contact your campaign finance analyst at >.

W/ the > being the RAD contact mainline or a link to RAD analyst search.

![rfai page language](https://cloud.githubusercontent.com/assets/22914750/21460467/a2e0da48-c916-11e6-9b62-e73ccdce42fe.png)

**Comment by emileighoutlaw** [comment]
Current:
> The RFAI letter explains what information the FEC needs from your committee. When composing your response, use our [website](https://beta.fec.gov/data/?search=&amp;search_type=committees) to access any reports and submissions you need. Additionally, the last paragraph of the RFAI lists your FEC analyst. Contact your analyst with any questions or concerns.

> Time constraints limit our ability to respond to your submitted responses or amendments. We will only reach out if we find additional discrepancies.

Proposed new:

> The RFAI letter explains what information the FEC needs from your committee. When composing your response, use this website's [data section](https://beta.fec.gov/data/?search=&amp;search_type=committees) to access any reports and submissions you need. 

> Resource constraints limit the FEC's ability to reach out when it receives your responses and amendments. If you have further questions, please contact the Reports Analysis Division at (202) 694-1130. Additionally, the last paragraph of the RFAI lists your FEC analyst. Contact your analyst with any questions or concerns.

@llienfec — do we really need to lose the "We will only reach out if we find additional discrepancies" sentence? It seems very helpful for folks to know that no news is good news.


Changes: 
- Minor rewording of second paragraph per RAD's request
- Moved all contact info to second paragraph
- Clarified what "Our website" means (b/c it actually means the data section of the website)
- Removes "We" POV, which we're deprecating now in favor of third-person "the FEC."

Pinging @AmyKort for review.

**Comment by noahmanger** [comment]
Ping on this.

**Comment by AmyKort** [comment]
Sorry--I totally dropped the ball on this one. It looks good to me, but I'd want @llienfec to take a look and also let us know if we need additional layers of review. Thanks!

**Comment by llienfec** [comment]
Sorry I dropped this too!!!  @emileighoutlaw Good question re: "We will only reach out if we find additional discrepancies" sentence.  Unfortunately no news isn't necessarily good news.  It just means that we don't have the resources to send everyone another letter to say whether or not their response was adequate.  (Apparently 2nd letters used to be sent, but before my time.)  If people have questions about the adequacy of their responses, we'd encourage them to contact their analyst.

**Comment by emileighoutlaw** [comment]
Makes perfect sense to me @llienfec. So how does this sound for the new content:

> The RFAI letter explains what information the FEC needs from your committee. When composing your response, use this website's [data section](https://beta.fec.gov/data/?search=&amp;search_type=committees) to access any reports and submissions you need. 

> Resource constraints limit the FEC's ability to reach out when it receives your responses and amendments. The last paragraph of the RFAI lists your FEC analyst. Contact your analyst with any questions or concerns. If you have further questions, please contact the Reports Analysis Division at (202) 694-1130.

**Comment by llienfec** [comment]
Looks great @emileighoutlaw.

**Comment by emileighoutlaw** [comment]
Edit is live: https://beta.fec.gov/registration-and-reporting/request-additional-information/ 🎉
