### ISSUE TITLE
Name not being passed to candidate information page

### ISSUE THREAD

**Issue by busterroni** [18F/FEC#560]
The name of a candidate who does not have any financial data is not being passed. For example, on [this](https://beta.fec.gov/data/candidate/P60009198/) candidate's page, the following message is given: "Sorry, we didn't find any financial data for **candidate** in the **2015–2016** election cycle", when it should be "Sorry, we didn't find any financial data for **Deez Nuts** in the **2015–2016** election cycle".

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1760

Thanks again!
